### ISSUE TITLE
[C_API] LGBM model returns different predictions on Python and C++

### ISSUE THREAD

**Issue by truecoder34** [microsoft/LightGBM#5822] opened 2023-04-07 08:53 UTC
## Description
I'm using LGBM in Conda to learn classifier with absolute default parameters.  Then I save this model to .txt file and reuse it in inference made with C++ API of LGBM. 
As a result I get completely wrong prediction on C++ API side. 

## Reproducible example
How I save model in Python : ```lgbm_clf.booster_.save_model(file_path) ```
How I make Load-Init-Predict in C++:
```
  BoosterHandle handle;
  int p;
  auto model = LGBM_BoosterCreateFromModelfile("lgbm_model.txt", &p, &handle);
  if(model != 0){
      std::cout << "[MODEL LOAD] Fail On Load！" << std::endl;
      exit(-1);
  }
  else{
      std::cout << "[MODEL LOAD] Success!" << std::endl;
  }

  FastConfigHandle fch;
  auto fastConfigHandle = LGBM_BoosterPredictForMatSingleRowFastInit(
    handle, 
    C_API_PREDICT_NORMAL, 
    0, 
    -1, 
    C_API_DTYPE_FLOAT64, 
    8128,
    "", 
    &fch);

  auto result = LGBM_BoosterPredictForMatSingleRowFast(fast_config_handle_, 
    input_preproc.data(), 
    &out_len,
    out_result);

  for (size_t i = 0; i < 9; i++) {
    std::cout << out_result[i] << " ";
  }
```

where ``` input_preproc ``` is a std vector of integers with (8128,1) shape.
**In Python** I see  : 
``` Prediction ::  [[4.09284964e-09 4.11144975e-09 9.99999872e-01 4.39910482e-09  8.14673222e-10 4.75892813e-09 4.95161555e-09 4.86100559e-08   5.58336916e-08]] ```

**In C++** : 
 ```0.300088 3.44493e-09 2.49066e-09 4.14752e-09 1.3418e-08 0.699912 2.72443e-09 2.45773e-09 3.56966e-09 ```

## Environment info

LightGBM version or commit hash:
_C++_ : 
cat VERSION.txt
3.3.5.99
_Python :_ 
lightgbm                  3.3.5           py310h419075a_0

Command(s) you used to install LightGBM

```shell
git clone --recursive https://github.com/microsoft/LightGBM
cd LightGBM
mkdir build
cd build
cmake ..
make -j4
```

## Additional Comments
I have seen in Issues problems with versions incompatibility , but I use the same Python and C++ version for now.  Are there any ideas how to investigate this problem, @guolinke  @chivee ?
Thank you in advance

**Comment by jmoralez** [comment] 2023-04-11 17:10
Hey @truecoder34, thanks for using LightGBM.

> where input_preproc is a std vector of integers

Does that mean that the element type of the vector is int? You're passing `C_API_DTYPE_FLOAT64`, so if you're using ints you'll get a wrong result because they will be interpreted as doubles.

**Comment by maxupp** [comment] 2023-04-18 10:44
We're facing related issues, running the same model in identical containers on different hosts, We have debugged to the point where LightGBM allocated CTYPES, and one host will give a `long`, the other a `long long`. We haven't been able to delve any deeper into this issue.

**Comment by jmoralez** [comment] 2023-04-19 04:39
Here's a minimal example that shows the same prediction, if you can provide one that doesn't we can provide further help, otherwise it'll be hard to find the root cause.

<details>
<summary>Python</summary>

```python
import numpy as np
import lightgbm as lgb

rng = np.random.RandomState(0)
X = rng.rand(100, 4)
y = rng.rand(100)
ds = lgb.Dataset(X, y)
params = {'num_leaves': 5, 'verbose': -1}
bst = lgb.train(params, ds, num_boost_round=2)
bst.save_model('model.txt')
sample = [[0.1, 0.2, 0.3, 0.4]]
print(bst.predict(sample)[0])
# 0.5196307987750819
```
</details>

<details>
<summary>C++</summary>

```c++
#include <iostream>
#include <LightGBM/c_api.h>

int main() {
    // Load the trained model from file
    std::string model_file = "model.txt";
    BoosterHandle handle;
    int num_iterations;
    LGBM_BoosterCreateFromModelfile(model_file.c_str(), &num_iterations, &handle);

    // Prediction setup
    double features[] = {0.1, 0.2, 0.3, 0.4};
    FastConfigHandle fch;
    LGBM_BoosterPredictForMatSingleRowFastInit(
            handle,
            C_API_PREDICT_NORMAL,
            0,
            -1,
            C_API_DTYPE_FLOAT64,
            4,
            "",
            &fch);

    // Predict
    int64_t out_len;
    double out_result;
    LGBM_BoosterPredictForMatSingleRowFast(fch,
                                           features,
                                           &out_len,
                                           &out_result);
    std::cout << "Result: " << out_result << std::endl;
    return 0;
}
// Result: 0.519631
```
</details>

**Comment by truecoder34** [comment] 2023-04-19 07:35
@jmoralez , Hi, thank you for your help. I found the issue on my side. I provide int data instead of double here `input_preproc.data()`. 

```
  auto result = LGBM_BoosterPredictForMatSingleRowFast(fast_config_handle_, 
    **input_preproc.data(),** 
    &out_len,
    out_result);
```

With double everything is ok.

BTW , if i switch to float on C++ side ? i mean use input float data and  C_API_DTYPE_FLOAT32  - i Again get wrong predictions. Do you know the way how to learn model on python with float support instead of double ? 

Thanks.

**Comment by jmoralez** [comment] 2023-04-19 21:59
@truecoder34 can you provide a reproducible example? Using `float features[] = {0.1, 0.2, 0.3, 0.4};` and `C_API_DTYPE_FLOAT32` in my example above yields the same result.

**Closed** 2023-05-20 04:03 UTC
Labels: question, awaiting response
