### ISSUE TITLE
why dose lightgbm.Dataset create one extra feature when read in libsvm file

### ISSUE THREAD

**Issue by unbreakablegao** [Microsoft/LightGBM#1775] opened 2018-10-22 11:08 UTC
<!--
Hi 
When I tried to load a subset of the iris dataset formated in libsvm as following:
1  1:7  2:3.2  3:4.7  4:1.4
1  1:6.4  2:3.2  3:4.5  4:1.5
1  1:6.9  2:3.1  3:4.9  4:1.5
0  1:6.3  2:3.3  3:6  4:2.5
0  1:5.8  2:2.7  3:5.1  4:1.9
0  1:7.1  2:3  3:5.9  4:2.1
0  1:6.3  2:2.9  3:5.6  4:1.8
... ...,

it was very weird that it yielded 5 feature names when there were actually 4 features. I am wondering what exactly is this extra feature.

the following is the code I was using:
```
train_data_lgb_dat = lgb.Dataset("iris_libsvm.txt")
params = {
        'boosting_type': 'gbdt'
        , 'objective': 'binary'
        , 'metric': 'auc'
        , 'learning_rate': 0.1
        , 'feature_fraction': 1
        , 'verbose': 1
        , 'is_unbalance': False
        , 'num_leaves': 4
    }
num_round = 200
lgb_1 = lgb.train(params, train_data_lgb_dat, num_round, verbose_eval=20)
>>> lgb_1.feature_name()
[u'Column_0', u'Column_1', u'Column_2', u'Column_3', u'Column_4']
```

thank you very much for your help.
<!--

**Comment by StrikerRUS** [comment] 2018-10-22 22:16
Duplicate of #1776 due to https://blog.github.com/2018-10-21-october21-incident-report/.

**Closed by StrikerRUS** 2018-10-22 22:16 UTC
