### ISSUE TITLE
PLZ provide an easier way to install lightgbm-gpu version

### ISSUE THREAD

**Issue by ctwangtz** [microsoft/LightGBM#3746] opened 2021-01-11 05:02 UTC
The method you provided is too complicated to install it easy, and I think  a code like "pip install lightgbm-gpu" is better.

**Comment by StrikerRUS** [comment] 2021-01-11 11:20
Closing as a duplicate of #2263.

@ctwangtz If you are on Window, you can try nightly releases which support GPU-training out of the box.

> Compiled library that is included in the wheel file supports both GPU and CPU versions out of the box. This feature is experimental and available only for Windows currently. To use GPU version you only need to install OpenCL Runtime libraries. For NVIDIA and AMD GPU they are included in the ordinary drivers for your graphics card, so no action is required. If you would like your AMD or Intel CPU to act like a GPU (for testing and debugging) you can install AMD APP SDK.

https://github.com/microsoft/LightGBM/tree/master/python-package#install-from-pypi-using-pip

**Closed by StrikerRUS** 2021-01-11 11:20 UTC
