### ISSUE TITLE
[python-package] `init_score` causes the predictions different

### ISSUE THREAD

**Issue by oooo26** [microsoft/LightGBM#6404] opened 2024-04-03 07:56 UTC
## Description

I want to use some prior predictions from other method as `init_score` and speed up training, but when setting this argument, predictions are quite different. I think I misunderstood this feature. How does it work?

## Reproducible example

```python
import pandas as pd
import lightgbm as lgb
from sklearn import datasets
from sklearn.linear_model import LinearRegression

diabetes = datasets.load_diabetes()
n, p = diabetes["data"].shape


def lgb_model(init_score):
    train_set = lgb.Dataset(
        data=diabetes["data"],
        label=diabetes["target"],
        feature_name=diabetes["feature_names"],
        init_score=init_score,
    )
    params = {
        "objective": "l2",
        "verbosity": -1,
        "seed": 0,
    }
    model = lgb.train(params, train_set)
    predictions = model.predict(diabetes["data"])
    return predictions


init_model = LinearRegression().fit(diabetes["data"], diabetes["target"])
results = pd.DataFrame(
    {
        "target": diabetes["target"],
        "init - None": lgb_model(None),
        "init - mean": lgb_model([diabetes["target"].mean()] * n),
        "init - linear": lgb_model(init_model.predict(diabetes["data"])),
    }
)

print(results.head())
```

And the results are:
```bash
   target  init - None  init - mean  init - linear
0   151.0   162.653224    10.519740     -39.368330
1    75.0    75.949063   -76.184421      13.700046
2   141.0   141.158077   -10.975407     -22.048918
3   206.0   217.419851    65.286367      56.010205
4   135.0   131.487873   -20.645611     -17.713920
```

After setting `init_score` from mean model or linear model, the results will change.

## Environment info

LightGBM version or commit hash: 4.3.0

Command(s) you used to install LightGBM

```shell
pip install lightgbm
```

macOS Sonoma 14.1
Python 3.10.13
Conda 24.1.2

**Comment by oooo26** [comment] 2024-04-03 08:06
Should I add the `init_score` to lgb prediction? It seems useful for this "l2" objective, but still weird for e.g. "tweedie".
```python
import pandas as pd
import lightgbm as lgb
from sklearn import datasets
from sklearn.linear_model import LinearRegression

diabetes = datasets.load_diabetes()
n, p = diabetes["data"].shape


def lgb_model(init_score):
    train_set = lgb.Dataset(
        data=diabetes["data"],
        label=diabetes["target"],
        feature_name=diabetes["feature_names"],
        init_score=init_score,
    )
    params = {
        "objective": "tweedie",  # change to tweedie
        "verbosity": -1,
        "seed": 0,
    }
    model = lgb.train(params, train_set)
    predictions = model.predict(diabetes["data"])
    if init_score is not None:
        predictions += init_score. # add init_score
    return predictions


init_model = LinearRegression().fit(diabetes["data"], diabetes["target"])
results = pd.DataFrame(
    {
        "target": diabetes["target"],
        "init - None": lgb_model(None),
        "init - mean": lgb_model([diabetes["target"].mean()] * n),
        "init - linear": lgb_model(init_model.predict(diabetes["data"])),
    }
)

print(results.head())
```
```bash
   target  init - None  init - mean  init - linear
0   151.0   157.811490   152.952215     207.116677
1    75.0    75.164031   152.952215      69.071033
2   141.0   140.120412   152.952215     177.882790
3   206.0   223.799875   152.952215     167.914458
4   135.0   119.464777   152.952215     129.462258
```

**Comment by jmoralez** [comment] 2024-04-05 17:56
Hey @oooo26, thanks for using LightGBM.

> Should I add the init_score to lgb prediction?

Yes

> It seems useful for this "l2" objective, but still weird for e.g. "tweedie"

You should be able to match the outputs of `init_score=None` if you set it to the same value that LightGBM starts the boosting from, which is different for each objective. For l2 is the mean of the target, but for tweedie is the log of that
https://github.com/microsoft/LightGBM/blob/28536a0a5d0c46598fbc930a63cec72399a969e4/src/objective/regression_objective.hpp#L468-L470

**Comment by oooo26** [comment] 2024-04-06 01:38
Thank you for helping!
Let me double check, for tweedie, I should set `init_score` as the log scale of initial predictions and, after fitting, still add the normal scale of them?

**Comment by oooo26** [comment] 2024-04-07 02:06
Oh I see. it should be like 
```python
model = lgb.train(params, train_set)
predictions = model.predict(diabetes["data"])
predictions = np.exp(np.log(predictions) + train_set.init_score)
```

It is a bit complex i think...but anyway, thank you!

**Comment by jmoralez** [comment] 2024-04-11 15:49
Yes, some objectives have a `ConvertOutput` method, which is used to translate the raw scores (which the model is trained to predict) to the actual scores (the ones we're interested in). In the case of Tweedie it's the exp (as you've correctly done) https://github.com/microsoft/LightGBM/blob/5dfe7168d42898b66da3513eb8cab68ef2b23eeb/src/objective/regression_objective.hpp#L460-L462

So another alternative would be to always predict the raw score, add the init score (which will be on the same "scale"), and then apply that transformation. So the following would be equivalent but maybe easier since for each objective you'd only need to apply the `ConvertOutput` method.

```python
    convert_output = np.exp  # for tweedie and poisson
    predictions = model.predict(diabetes["data"], raw_score=True)
    if init_score is not None:
        predictions += init_score
    return convert_output(predictions)
```

**Comment by jmoralez** [comment] 2024-04-11 15:52
Closing since I believe the issue has been solved, feel free to reopen if you run into any more problems.

**Closed by jmoralez** 2024-04-11 15:52 UTC
Labels: question
