### ISSUE TITLE
[python-package] LGBMClassifier objective can be gibberish for multiclass, but throws a warning for binary

### ISSUE THREAD

**Issue by rosscleung** [microsoft/LightGBM#5616] opened 2022-12-02 19:21 UTC
## Description
The sklearn LGBMClassifier's objective can be fed gibberish IF the target classes is > 2. Otherwise a correct warning is thrown.

## Reproducible example
```
from lightgbm import LGBMClassifier
import pandas as pd

```
**This throws an error because the target only has 2 classes**
```
model = LGBMClassifier(objective="ajkl;sdfal;jk",)
model.fit(pd.DataFrame({"a":[1,1,1,1,1,1],"b":[123,123,123,123,123,123]}),pd.Series([0,0,0,1,1,1]))

```
**This won't throw an error and as you can see below, the code base quietly corrects the _concrete_ self.objective_, but keeps the gibberish in self.objective.**
```
model = LGBMClassifier(objective="ajkl;sdfal;jk",)
model.fit(pd.DataFrame({"a":[1,1,1,1,1,1],"b":[123,123,123,123,123,123]}),pd.Series([0,0,0,1,1,2]))
model.objective_ # returns "multiclass". Code base says objective_ is the concrete objective actually used. Code quietly corrected the gibberish to multiclass. 
model.objective # returns "ajkl;sdfal;jk". This means the object still kept the original gibberish objective.

```

## Environment info
lightgbm                  3.3.2            py37hcd2ae1e_0    conda-forge
LightGBM version or commit hash:

Command(s) you used to install LightGBM

```shell

```

## Additional Comments
This quiet bug is not model-breaking, but can lead to unintended behavior. I'm not sure what happens if we provide a custom callable objective function, I have not tested that.

**Comment by jmoralez** [comment] 2022-12-08 06:46
Thanks for raising this and for the reproducible example @rosscleung. However this doesn't happen in the master branch, I get `LightGBMError: Number of classes must be 1 for non-multiclass training` on the fit step, which comes from here https://github.com/microsoft/LightGBM/blob/6fa4673f69fa377477e74f986e216c5c186b5b1f/src/io/config.cpp#L286-L299 Not sure what fixed it because that code hasn't changed. I'm going to close this as it seems like it isn't a problem anymore.

**Closed by jmoralez** 2022-12-08 06:46 UTC
Labels: question
