### ISSUE TITLE
Evaluating loaded model on new data

### ISSUE THREAD

**Issue by minaeann** [microsoft/LightGBM#4861] opened 2021-12-06 03:09 UTC
## Summary

Is there a way to evaluate loaded model on a new model with no access to its training procedure? For continue training of models, it would be useful to be able to evaluate the 0th iteration of a model (i.e., without adding new trees).

The tried out way is to use .eval() method, which returns `AttributeError: 'Booster' object has no attribute 'train_set'`. It looks like the [workaround](https://stackoverflow.com/questions/54859058/evaluating-test-dataset-using-eval-in-lightgbm) would be to add keep_training_booster=True as an argument to lgb.train. However, with no access to training procedure of this model it is imposible. Is there any other way to do it currently?

**Comment by jameslamb** [comment] 2021-12-06 03:59
Thanks for using LightGBM!

We need a bit more information before answering this. Can you please provide:

* the version of `lightgbm` you're using and how you installed it
* code that reproduces this error (including information about specifically what you mean by "loaded model")
    - a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) if possible

**Comment by minaeann** [comment] 2021-12-07 01:31
Thanks for the prompt response! 

I am using lightgbm-3.3.1. on Windows 11. Installed with `pip install lightgbm`.

It is a ranking application of LightGBM. 

Minimal reproducible example:
```
# generate random data 
data = np.random.rand(1000, 10) # 1000 entities, each contains 10 features
label = np.random.randint(2, size=1000)
groups = [100] * 10 # there are 10 queries with 100 docs each
dtrain = lgb.Dataset(data, label=label, group=groups, free_raw_data=False)

bst = lgb.Booster(model_file="baseline.txt")
print("Evaluation of the initial model on all data:")
bst.eval(data=dtrain, name='train') # this is the line that does not work as mentioned in the first message
```

**Comment by shiyu1994** [comment] 2021-12-08 08:14
@minaeann Thanks for using LightGBM. Though the loaded model cannot `eval` on newly constructed data, will `predict` with the raw new data feasible for you? For example,
```python
import numpy as np
import lightgbm as lgb

# generate random data 
data = np.random.rand(1000, 10) # 1000 entities, each contains 10 features
label = np.random.randint(2, size=1000)
groups = [100] * 10 # there are 10 queries with 100 docs each
# dtrain = lgb.Dataset(data, label=label, group=groups, free_raw_data=False)

bst = lgb.Booster(model_file="baseline.txt")
print("Evaluation of the initial model on all data:")
scores = bst.predict(data) # this is the line that does not work as mentioned in the first message
# compute the metric that you want with 'scores', 'label' and 'groups'
```

**Comment by minaeann** [comment] 2021-12-10 05:30
Thank you. As far as I understood from your answer, there is no fully automatic way to do it currently in lightGBM (meaning just call one method). For completeness and people possibly looking for the same answer, I put my solution here. Please, let me know if this computation does not correspond to the way LightGBM computes NDCGs internally with `'metric':'ndcg'`, since I am interested in comparison of NDCG without training and on 1st, 2nd, etc iterations of training.

```
import numpy as np
import lightgbm as lgb
from sklearn.metrics import ndcg_score

# generate random data 
data = np.random.rand(1000, 10) # 1000 entities, each contains 10 features
label = np.random.randint(2, size=1000)
groups = [100] * 10 # there are 10 queries with 100 docs each
# dtrain = lgb.Dataset(data, label=label, group=groups, free_raw_data=False)

bst = lgb.Booster(model_file="baseline.txt")
print("Evaluation of the initial model on all data:")
scores = bst.predict(data)

eval_at = [1, 3, 5]
ndcgs = [[] for _ in range(len(eval_at))]
for num_elements in groups:
    current_range = range(current_index, current_index + num_elements)
    true_relevance = np.asarray([label[current_range]])
    query_scores = np.asarray([scores[current_range]])

    for i, k in enumerate(eval_at):
        ndcgs[i].append(ndcg_score(true_relevance, query_scores, k=k))

    current_index = current_index + num_elements
        
avg_ndcgs = np.mean(ndcgs, axis=1)
print(f'Average NDCGs at 0th iteration at positions {eval_at} are {avg_ndcgs}, respectively')
```

**Comment by jameslamb** [comment] 2024-04-24 03:50
Closing this due to lack of updates.

**Closed by jameslamb** 2024-04-24 03:50 UTC
Labels: question
