### ISSUE TITLE
Pass in a probability for each feature when sampling features

### ISSUE THREAD

**Issue by wmmxk** [microsoft/LightGBM#6087] opened 2023-09-09 15:34 UTC
Currently, lightgbm supports pass in interaction_constraints as prior when sampling features. 

https://github.com/microsoft/LightGBM/blob/68621628cec76c5580338b24210b3587f8704924/src/treelearner/col_sampler.hpp#L27

I was wondering it is possible add such a feature so a user can pass in a probability vector for all the features when sampling features.

**Comment by jameslamb** [comment] 2023-09-09 20:32
Thanks for your interest in LightGBM.

We already have several other such requests for "per-feature probability of features being selected":

* #2542
* #4605
* #4962

I *think* you are asking for the same thing as #4605, and that this can be closed as a duplicate of that. Can you please read #4605 and confirm? If your request is different from that one, please explain how.

----

Also note... I've modified your original post so the link to LightGBM's code is anchored to a specific commit. That way, as the library evolves it'll always be possible for someone reading your post in the future to understand what line you were pointing to.

If you don't know how to do that, you can read about it at https://docs.github.com/en/repositories/working-with-files/using-files/getting-permanent-links-to-files.

**Comment by wmmxk** [comment] 2023-09-10 14:17
@jameslamb  I really appreciate your reply and modifiying my request and instructions about how to cite a line by a permanent link.

My request is the same as [Probability measure for features #4605](https://github.com/microsoft/LightGBM/issues/4605). It looks the [cost efficient gradient boosting](https://github.com/svenpeter42/LightGBM-CEGB) might do a similar job. I will look into the implementation in that repo.

**Comment by jameslamb** [comment] 2023-09-10 23:27
Ok sure, no problem! We'll close this then.

**Closed by jameslamb** 2023-09-10 23:27 UTC
Labels: feature request
