### ISSUE TITLE
Rscript command does not work

### ISSUE THREAD

**Issue by thecpshah** [Microsoft/LightGBM#2027] opened 2019-02-25 14:55 UTC
## Environment info

Operating System: Windows

CPU/GPU model: CPU

C++/Python/R version: R

LightGBM version or commit hash: Current

## Error message

When I execute the command `Rscript build_r.r`, I get the following error: `'Rscript' is not recognized as an internal or external command, operable program or batch file.`

## Steps to reproduce

1. Follow the steps here https://github.com/Microsoft/LightGBM/tree/master/R-package
![capture](https://user-images.githubusercontent.com/10298891/53345671-58e0db00-390d-11e9-9b4c-b2e9d8baf378.PNG)

**Comment by StrikerRUS** [comment] 2019-02-25 19:15
@thecpshah Please provide your `PATH`

**Comment by jameslamb** [comment] 2019-02-26 04:53
@thecpshah to elaborate on @StrikerRUS 's question, this error almost always means you don't have `Rscript` on your path.

I notice you're in a conda cmd session...did you use `conda` as your R installer, instead of downloading and installing R for Windows?

Also, let's confirm that the issue is with our script and not some misconfiguration in your environment. Could you share the result of running this command from that prompt:

```
Rscript -e "print('hello StrikerRUS and jameslamb')"
```

**Comment by thecpshah** [comment] 2019-02-26 09:24
Thanks for your responses.

I downloaded R from CRAN. I used Conda prompt to clone git repo.

Please see attached screenshot for PATH.
![capture](https://user-images.githubusercontent.com/10298891/53401690-33ed7600-39a8-11e9-80ce-4ec3b5cbc310.PNG)

When I run the command, `Rscript -e "print('hello StrikerRUS and jameslamb')"`

I get following:

`'Rscript' is not recognized as an internal or external command, operable program or batch file.`

**Comment by Laurae2** [comment] 2019-02-26 10:33
@thecpshah Include your R's Rscript to your PATH then re run a command
prompt. It should be in (???)/R/bin/x64 in Windows.

**Comment by thecpshah** [comment] 2019-02-26 11:55
Ok, this works. Once I added it in the PATH, this command work `Rscript -e "print('hello StrikerRUS and jameslamb')"`

But when I execute `Rscript build_r.R` in `LightGBM` directory, I get message `There is no package Roxygen2`. Once I installed it, it complains that `devtools` isn't installed.

**Comment by thecpshah** [comment] 2019-02-26 13:38
I am able to build `LightGBM` and ran the test example.

It runs, however, it would be good if expected output was available. Please see the output attached.

Thanks for all the help.
![capture](https://user-images.githubusercontent.com/10298891/53416650-d9fea780-39cb-11e9-915d-51ff2d556a3d.PNG)

**Comment by jameslamb** [comment] 2019-03-02 04:16
@thecpshah Oh good, I am glad it worked for you! I am going to close this issue.

Thanks for the help @Laurae2

**Closed by jameslamb** 2019-03-02 04:16 UTC
Labels: r-package
