### ISSUE TITLE
[R-package] R package fails with development version of testthat

### ISSUE THREAD

**Issue by hadley** [microsoft/LightGBM#5513] opened 2022-09-27 12:52 UTC
This is a courtesy notice to let you know that I see a failure of lightgbm with dev testthat:

```
      ── 1. Failure ('test_lgb.Booster.R:474'): Booster$eval() should work on a Datase
      `eval_in_mem` not identical to `eval_from_file`.
      Objects equal but not identical
```

I suspect this is just a numeric issue, but when I tried to debug it further I couldn't load your package because you have an invalid `DESCRIPTION`:

```
Version: ~~VERSION~~
Date: ~~DATE~~
```

I'm sure you have some good reason for this but unfortunately I don't have the time to dig in to it, so you'll need to debug yourself.

**Comment by jameslamb** [comment] 2022-09-27 12:56
Thanks very much for taking the time to warn us! I'll try building the dev version of `{lightgbm}` against the dev version of `{testthat}` and see what I can find.

> I'm sure you have some good reason for this

We do: https://github.com/tidymodels/bonsai/issues/34#issuecomment-1187589193

**Comment by hadley** [comment] 2022-09-27 20:17
Just to let you know, we're planning on submitting testthat to CRAN on Oct 7.

**Comment by jameslamb** [comment] 2022-09-27 20:31
Thanks for the notice! I'll try to reproduce the error you've reported in the next few days, and if I can we'll try to put up a patch release on CRAN.

That might be necessary anyway based on a recent, unrelated failure we're seeing in one of the CRAN checks (#5502 ).

**Comment by jmoralez** [comment] 2022-10-07 18:22
Sorry, I can't reproduce this error. This may be a noob question but did I miss something? I did the following:
1. Install testthat from github.
2. Install lightgbm version 3.3.0 (I also tried the master branch).
3. Run the tests (all pass).

Here's my session info:
```
> Rscript -e 'library(testthat); library(lightgbm); sessionInfo()'
R version 4.2.0 (2022-04-22)
Platform: aarch64-apple-darwin20 (64-bit)
Running under: macOS Monterey 12.6

Matrix products: default
BLAS:   /Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/lib/libRblas.0.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] lightgbm_3.3.3      testthat_3.1.4.9000

loaded via a namespace (and not attached):
 [1] compiler_4.2.0    Matrix_1.4-1      magrittr_2.0.3    R6_2.5.1         
 [5] cli_3.4.1         parallel_4.2.0    grid_4.2.0        data.table_1.14.2
 [9] jsonlite_1.8.2    brio_1.1.3        rlang_1.0.6       lattice_0.20-45 
```

**Comment by hadley** [comment] 2022-10-07 19:00
I can't reproduce it now either.

**Comment by jameslamb** [comment] 2022-10-09 16:02
I'm going to close this issue, it seems that there is nothing to be done right now, given that:

* neither of you is able to reproduce this
* I just observed multiple successful runs of `{lightgbm}` on a wide range of win-builder and R Hub environments (see description of #5525), all using the newest version of `{testthat}` (3.1.5)

Thanks for the report and warning of the new release, though, and for maintaining `{testthat}` itself!

And thanks @jmoralez for helping to validate this.

**Closed by jameslamb** 2022-10-09 16:02 UTC
Labels: r-package
