### ISSUE TITLE
[python] Performance - Conda (anaconda vs conda-forge channel)

### ISSUE THREAD

**Issue by jameswinegar** [microsoft/LightGBM#3414] opened 2020-09-29 04:35 UTC
Discussed with @jameslamb around some performance issues when installing from conda-forge vs anaconda channel. 

Anaconda's default channel produces around ~20x better performance. This is likely due to compiling BLAS and MKL with their default distribution. Given the popularity of the conda-forge package, it might be worth investigating performance improvements that can be made to drive the adoption of LightGBM further.

I understand that the conda-forge package is not maintained by the core LightGBM team, but was advised by @jameslamb to post this anyways. 

Here are the recipes and some helpful links:
https://github.com/AnacondaRecipes/lightgbm-feedstock
https://github.com/conda-forge/lightgbm-feedstock

It seems like this is the key difference between the two at the time of the fork, plus any recent changes they've made since the fork
https://github.com/AnacondaRecipes/lightgbm-feedstock/commit/38b13c09baa2399d4f2fc8b2125e3261830edca2
https://github.com/AnacondaRecipes/lightgbm-feedstock/compare/master...conda-forge:master

```
name: env-name
channels:
  #- conda-forge
dependencies:
  - python=3.7
  - lightgbm>=2.2.2
  - scikit-learn>=0.23.0
Perf:
    LGBMRegression training time: 0:00:24.775091

name: env-name
channels:
  - conda-forge
dependencies:
  - python=3.7
  - lightgbm>=2.2.2
  - scikit-learn>=0.23.0

Perf:
    LGBMRegression training time: 0:07:16.498950
```

Code to reproduce-below

```{bash}
#!/bin/bash
CONDA_BASE_PATH="/path/to/base/env"
ENV_NAME="env-name"
perftest () {
    conda env remove --quiet --name ${ENV_NAME}
    conda env update --quiet -f environment.yml
    ${CONDA_BASE_PATH}/${ENV_NAME}/bin/python test.py
}

tee environment.yml  <<EOF
name: ${ENV_NAME}
channels:
  #- conda-forge
dependencies:
  - python=3.7
  - lightgbm>=2.2.2
  - scikit-learn>=0.23.0
EOF
perftest
 
tee environment.yml  <<EOF
name: ${ENV_NAME}
channels:
  - conda-forge
dependencies:
  - python=3.7
  - lightgbm>=2.2.2
  - scikit-learn>=0.23.0
EOF
perftest
```

```{python}
from datetime import datetime
import numpy as np
from lightgbm import LGBMRegressor
from sklearn.datasets import make_regression
from sklearn.model_selection import train_test_split

n_samples, n_features = 10000000, 30
rng = np.random.RandomState(0)
X, y = make_regression(n_samples, n_features, random_state=rng)
sample_weight = rng.rand(n_samples)
X_train, X_test, y_train, y_test, sw_train, sw_test = train_test_split(
    X, y, sample_weight, random_state=rng)

t1 = datetime.now()
reg = LGBMRegressor()
reg.fit(X_train, y_train)
t2 = datetime.now()
print("Perf")
print("    LGBMRegression training time:", t2-t1)
```

**Comment by guolinke** [comment] 2020-09-29 05:14
did you try to set num_thread to the same number in benchmark?

**Comment by jameswinegar** [comment] 2020-09-29 05:35
@guolinke these are on the same machine running in parallel. Nothing special was done for the configuration outside of what's shown here. 

If you would like me to test I can run an additional test.

**Comment by guolinke** [comment] 2020-09-29 07:41
@jameswinegar yeah, I guess some default environment variables may are different, like omp_num_threads, and cause the different performance. So it is worthy to try the fixed num_threads in the LightGBM side.

**Comment by StrikerRUS** [comment] 2020-09-29 11:28
> So it is worthy to try the fixed num_threads in the LightGBM side.

Probably it worth to try to pin the following env variables as well:
```
MKL_NUM_THREADS
NUMEXPR_NUM_THREADS
OMP_NUM_THREADS
OPENBLAS_NUM_THREADS
VECLIB_MAXIMUM_THREADS
BLIS_NUM_THREADS
```

**Comment by jameswinegar** [comment] 2020-09-29 19:54
okay, well I wasn't able to replicate the 20x performance difference again. There might have been someone running an additional workload. 

I did this on a few machines and set all environment variables equal to number of cores.

Still seeing around a 10-15% difference in the performance between conda-forge and anaconda channel, favoring the anaconda channel.

**Comment by StrikerRUS** [comment] 2020-09-30 14:14
ping @aldanor and @synapticarbors as [maintainers of the conda-forge feedstock](https://github.com/conda-forge/lightgbm-feedstock#feedstock-maintainers).

**Comment by StrikerRUS** [comment] 2021-01-09 14:58
@jameslamb I don't think we can do anything with this issue. And
> Still seeing around a 10-15% difference 

doesn't seem like something critical. Can we close this?

**Comment by jameslamb** [comment] 2021-01-09 18:37
I'd like to leave it open for a little bit, if that's alright. @jameswinegar gave us what looks like a pretty clean reproducible example, and I would like to come back and look into this in the near future.

**Comment by StrikerRUS** [comment] 2021-01-09 23:53
@jameslamb OK, got it.

**Comment by jameslamb** [comment] 2021-08-16 02:55
@jameswinegar @StrikerRUS I finally came back to investigating this today.

**I was not able to reproduce any notable performance differences**.

I then tried 3 different envs:

* `conda-forge-base` = `lightgbm`, `numpy`, and `scikit-learn` installed from `conda-forge`
* `defaults-base` = `lightgbm`, `numpy`, and `scikit-learn` installed from the default channels
* `conda-forge-with-mkl` = identical to `conda-forge-base`, but explicitly requesting that `mkl` be installed too.

I found that individual runs could differ by 15-30%, but that the timing distributions were very similar. Here are the results from running training 5 times for each environment.

| env                 | min   | median | mean  | max   |
|:-------------------:|:-----:|:------:|:-----:|:-----:|
|conda-forge-base     | 1m03s | 1m07s  | 1m09s | 1m17s |
|defaults-base        | 1m01s | 1m03s  | 1m09s | 1m23s |
|conda-forge-with-mkl | 1m03s | 1m04s  | 1m06s | 1m17s |

Based on these findings, I wonder if the differences you observed were random variations in training time and not something structurally different between those packages. Training times could differ based on other factors like resource contention with other processes, for example.

### how I tested this

Before starting, I ran `pip uninstall lightgbm` and `conda uninstall -n base -y lightgbm`, to be very sure that there weren't other versions of the Python library laying around that might get loaded.

I also used `htop` to monitor training, and can confirm based on that that:

1. Memory utilization never approached 75%, so I don't think `lightgbm` started swapping at any point.
2. All 4 cores on my laptop were fully utilized at some points during training, so I think both the version from `conda-forge` and the one from the default channels had OpenMP linked correctly.

I chose 3.1.1 (released [in December 2020](https://github.com/microsoft/LightGBM/releases/tag/v3.1.1)) because that is the latest version available on the default channels (https://anaconda.org/anaconda/lightgbm).

Inspired by @jameswinegar's excellent example, I created the following testing code that is a bit stricter about using only one page source (either conda-forge or defaults) regardless of any local conda config.

```shell
conda_perftest() {
    local channel=${1}
    local packages="${2}"
    local package_file="${3}"
    source deactivate
    echo "removing env 'lgb'"
    conda env remove \
        --yes \
        --name lgb
    echo "creating environment 'lgb'"
    conda create \
        --yes \
        --name lgb \
        --strict-channel-priority \
        --override-channels \
        --channel ${channel} \
            python=3.7 \
            ${packages}
    echo "done creating environment"
    conda list \
        --name lgb \
        --show-channel-urls > "${package_file}"
    source activate lgb
    echo "wrote 'conda-list' details to ${package_file}"
    for i in {1..5}; do
        echo "testing iteration ${i}/5"
        python test.py
    done
    echo "done running tests"
}
```

Then ran that oonce for each of the environments mentioned above.

```shell
# conda-forge base env
conda_perftest \
    conda-forge \
    "lightgbm=3.1.1 numpy=1.20.3 scikit-learn=0.24.2" \
    conda-forge-base.txt

# default channels base env
conda_perftest \
    defaults \
    "lightgbm=3.1.1 numpy=1.20.3 scikit-learn=0.24.2" \
    defaults-base.txt

# conda-forge env including mkl
conda_perftest \
    conda-forge \
    "lightgbm=3.1.1 mkl=2021.3.0 numpy=1.20.3 scikit-learn=0.24.2" \
    conda-forge-with-mkl.txt
```

<details><summary>conda-forge-base (click me)</summary>

**timings**

```text
LGBMRegression training time: 0:01:07.792692
LGBMRegression training time: 0:01:03.474189
LGBMRegression training time: 0:01:04.646864
LGBMRegression training time: 0:01:17.710797
LGBMRegression training time: 0:01:16.981514
```

**environment with channels**

```text
# packages in environment at /Users/jlamb/miniconda3/envs/lgb:
#
# Name                    Version                   Build  Channel
ca-certificates           2021.5.30            h033912b_0    conda-forge
certifi                   2021.5.30        py37hf985489_0    conda-forge
joblib                    1.0.1              pyhd8ed1ab_0    conda-forge
libblas                   3.9.0           11_osx64_openblas    conda-forge
libcblas                  3.9.0           11_osx64_openblas    conda-forge
libcxx                    12.0.1               habf9029_0    conda-forge
libffi                    3.3                  h046ec9c_2    conda-forge
libgfortran               5.0.0           9_3_0_h6c81a4c_23    conda-forge
libgfortran5              9.3.0               h6c81a4c_23    conda-forge
liblapack                 3.9.0           11_osx64_openblas    conda-forge
libopenblas               0.3.17          openmp_h3351f45_1    conda-forge
lightgbm                  3.1.1            py37h9af6487_0    conda-forge
llvm-openmp               12.0.1               hda6cdc1_1    conda-forge
ncurses                   6.2                  h2e338ed_4    conda-forge
numpy                     1.20.3           py37h84c02c4_1    conda-forge
openssl                   1.1.1k               h0d85af4_0    conda-forge
pip                       21.2.4             pyhd8ed1ab_0    conda-forge
python                    3.7.10          h7728216_100_cpython    conda-forge
python_abi                3.7                     2_cp37m    conda-forge
readline                  8.1                  h05e3726_0    conda-forge
scikit-learn              0.24.2           py37h572704e_1    conda-forge
scipy                     1.7.1            py37h4e3cf02_0    conda-forge
setuptools                49.6.0           py37hf985489_3    conda-forge
sqlite                    3.36.0               h23a322b_0    conda-forge
threadpoolctl             2.2.0              pyh8a188c0_0    conda-forge
tk                        8.6.10               h0419947_1    conda-forge
wheel                     0.37.0             pyhd8ed1ab_1    conda-forge
xz                        5.2.5                haf1e3a3_1    conda-forge
zlib                      1.2.11            h7795811_1010    conda-forge
```

</details>

<details><summary>defaults-base (click me)</summary>

**timings**

```text
LGBMRegression training time: 0:01:16.464967
LGBMRegression training time: 0:01:01.655643
LGBMRegression training time: 0:01:03.510746
LGBMRegression training time: 0:01:02.061248
LGBMRegression training time: 0:01:23.532132
```

**environment with channels**

```text
# packages in environment at /Users/jlamb/miniconda3/envs/lgb:
#
# Name                    Version                   Build  Channel
blas                      1.0                         mkl    defaults
ca-certificates           2021.7.5             hecd8cb5_1    defaults
certifi                   2021.5.30        py37hecd8cb5_0    defaults
intel-openmp              2021.3.0          hecd8cb5_3375    defaults
joblib                    1.0.1              pyhd3eb1b0_0    defaults
libcxx                    10.0.0                        1    defaults
libffi                    3.3                  hb1e8313_2    defaults
libgfortran               3.0.1                h93005f0_2    defaults
lightgbm                  3.1.1            py37h23ab428_0    defaults
llvm-openmp               10.0.0               h28b9765_0    defaults
mkl                       2021.3.0           hecd8cb5_517    defaults
mkl-service               2.4.0            py37h9ed2024_0    defaults
mkl_fft                   1.3.0            py37h4a7008c_2    defaults
mkl_random                1.2.2            py37hb2f4e1b_0    defaults
ncurses                   6.2                  h0a44026_1    defaults
numpy                     1.20.3           py37h4b4dc7a_0    defaults
numpy-base                1.20.3           py37he0bd621_0    defaults
openssl                   1.1.1k               h9ed2024_0    defaults
pip                       21.0.1           py37hecd8cb5_0    defaults
python                    3.7.11               h88f2d9e_0    defaults
readline                  8.1                  h9ed2024_0    defaults
scikit-learn              0.24.2           py37hb2f4e1b_0    defaults
scipy                     1.6.2            py37hd5f7400_1    defaults
setuptools                52.0.0           py37hecd8cb5_0    defaults
six                       1.16.0             pyhd3eb1b0_0    defaults
sqlite                    3.36.0               hce871da_0    defaults
threadpoolctl             2.2.0              pyhbf3da8f_0    defaults
tk                        8.6.10               hb0a8c7a_0    defaults
wheel                     0.37.0             pyhd3eb1b0_0    defaults
xz                        5.2.5                h1de35cc_0    defaults
zlib                      1.2.11               h1de35cc_3    defaults
```

</details>

<details><summary>conda-forge-with-mkl (click me)</summary>

**timings**

```text
LGBMRegression training time: 0:01:04.938907
LGBMRegression training time: 0:01:03.784449
LGBMRegression training time: 0:01:04.546341
LGBMRegression training time: 0:01:04.911997
LGBMRegression training time: 0:01:17.063900
```

**environment with channels**

```text
# packages in environment at /Users/jlamb/miniconda3/envs/lgb:
#
# Name                    Version                   Build  Channel
ca-certificates           2021.5.30            h033912b_0    conda-forge
certifi                   2021.5.30        py37hf985489_0    conda-forge
joblib                    1.0.1              pyhd8ed1ab_0    conda-forge
libblas                   3.9.0           11_osx64_openblas    conda-forge
libcblas                  3.9.0           11_osx64_openblas    conda-forge
libcxx                    12.0.1               habf9029_0    conda-forge
libffi                    3.3                  h046ec9c_2    conda-forge
libgfortran               5.0.0           9_3_0_h6c81a4c_23    conda-forge
libgfortran5              9.3.0               h6c81a4c_23    conda-forge
liblapack                 3.9.0           11_osx64_openblas    conda-forge
libopenblas               0.3.17          openmp_h3351f45_1    conda-forge
lightgbm                  3.1.1            py37h9af6487_0    conda-forge
llvm-openmp               12.0.1               hda6cdc1_1    conda-forge
mkl                       2021.3.0           h08c4f10_555    conda-forge
ncurses                   6.2                  h2e338ed_4    conda-forge
numpy                     1.20.3           py37h84c02c4_1    conda-forge
openssl                   1.1.1k               h0d85af4_0    conda-forge
pip                       21.2.4             pyhd8ed1ab_0    conda-forge
python                    3.7.10          h7728216_100_cpython    conda-forge
python_abi                3.7                     2_cp37m    conda-forge
readline                  8.1                  h05e3726_0    conda-forge
scikit-learn              0.24.2           py37h572704e_1    conda-forge
scipy                     1.7.1            py37h4e3cf02_0    conda-forge
setuptools                49.6.0           py37hf985489_3    conda-forge
sqlite                    3.36.0               h23a322b_0    conda-forge
tbb                       2021.3.0             h940c156_0    conda-forge
threadpoolctl             2.2.0              pyh8a188c0_0    conda-forge
tk                        8.6.10               h0419947_1    conda-forge
wheel                     0.37.0             pyhd8ed1ab_1    conda-forge
xz                        5.2.5                haf1e3a3_1    conda-forge
zlib                      1.2.11            h7795811_1010    conda-forge
```

</details>

**Comment by jameswinegar** [comment] 2021-08-16 03:47
@jameslamb I had found a rouge c++ process running on the machine that when executed under certain conditions caused contention.

It is good that we have solid benchmarking we can do to compare now at the least.

**Comment by jameslamb** [comment] 2021-08-16 18:26
Ah ok great, thanks very much! I think then that this issue can be closed for now. Appreciate you bringing it up and putting all that effort into a reproducible example, that made it possible to get to an answer we could feel confident in.

**Closed by jameslamb** 2021-08-16 18:26 UTC
Labels: question

**Comment by StrikerRUS** [comment] 2021-08-17 17:38
@jameslamb Thanks a lot for investigating this issue!
