### ISSUE TITLE
Index out of bounds exception in LightGBM when using LGBM_DatasetCreateByReference and LGBM_BoosterResetTrainingData

### ISSUE THREAD

**Issue by mjmckp** [microsoft/LightGBM#3152] opened 2020-06-05 06:26 UTC
Using LGBM_DatasetCreateByReference and LGBM_BoosterResetTrainingData causes in index out of bounds exception:

![image](https://user-images.githubusercontent.com/7776787/83840218-59d3ff80-a741-11ea-9023-1efb8be3a9ce.png)

Steps to reproduce:
- Clone LightGBM.Net from https://github.com/rca22/LightGBM.Net
- ~~Switch to the `update_jun_20` branch~~ (no longer necessary, use master branch)
- Put a Debug build of LightGBM (built from master) in the `LightGBM.Net\native\Debug` folder
- Make the Dataset constructor [here](https://github.com/rca22/LightGBM.Net/blob/a73b8771a21811ce3da5e8561ad8cfc8f140addf/LightGBMNet.Train/Interface/Dataset.cs#L210) public instead of private.
- Uncomment and run the test [BoosterTest.ResetTrainingData](https://github.com/rca22/LightGBM.Net/blob/d7fbe5bd41230eda74e7bf497a38b984db655eb7/LightGBMNet.Test/BoosterTest.cs#L56) in LightGBMNet.Train.Test

All this test does is create a dataset, then create a second dataset from the first by taking half the rows, and then calls `LGBM_BoosterResetTrainingData` on the booster with the second dataset.

Note that this used to work with a previous version of LightGBM built from master last year.

**Comment by StrikerRUS** [comment] 2020-06-09 00:07
@mjmckp Hi!
The same request as in #3151: please provide a reproducible example that doesn't rely on `LightGBM.Net`.

**Comment by mjmckp** [comment] 2020-06-09 00:50
I don't have the time to reproduce these errors in some other way, unfortunately. I don't think it's unreasonable to use the unit tests of LightGBM.NET to reproduce the error, the tests are simple and self-contained, and the native DLL is easily debugged with Visual Studio using mixed-mode debugging.  These are genuine bugs in LightGBM, the same tests passed with a previous version of the native DLL.

**Comment by jameslamb** [comment] 2020-06-09 03:44
> I don't have the time to reproduce these errors in some other way, unfortunately

The group of maintainers here is also a small group of volunteers with limited time, and we cannot take on the task of reproducing a bug using a library that we do not maintain. We will be happy to help you when you can find time to reproduce this issue using only the software managed in this repo.

**Comment by guolinke** [comment] 2020-06-22 01:02
@mjmckp I think check this when I have time.

**Comment by mjmckp** [comment] 2020-06-22 01:36
@guolinke Thanks a lot.  I've updated the reproduction instructions above to use the master branch, now you will need to re-enable the failing test and corresponding failing constructor as described.

**Comment by guolinke** [comment] 2020-07-02 06:27
Hi @mjmckp 
It indeed is hard to debug, it keeps throwing the `argument to num_threads clause must be positive`, even if I add checks before all #omp num_threads(). And in these tests, it seems  I cannot print logs from LightGBM dll side. 
I am familiar with C# and  its test environment. It will be better if you wrap it to a reproduce console problem that I can easily get in.

And I got the different errors, regarding to ResetTrainingData:

Test Name:	LightGBMNet.Train.Test.BoosterTest.ResetTrainingData
Test FullName:	LightGBMNet.Test.LightGBMNet.Train.Test.BoosterTest.LightGBMNet.Train.Test.BoosterTest.ResetTrainingData
Test Source:	D:\src\LightGBM.Net\LightGBMNet.Test\BoosterTest.cs : line 58
Test Outcome:	Failed
Test Duration:	0:00:00

Test Name:	LightGBMNet.Train.Test.BoosterTest.ResetTrainingData
Test Outcome:	Failed
Result StackTrace:	
at LightGBMNet.Train.Booster..ctor(Parameters parameters, Dataset trainset, Dataset validset) in D:\src\LightGBM.Net\LightGBMNet.Train\Interface\Booster.cs:line 170
   at LightGBMNet.Train.Test.BoosterTest.ResetTrainingData() in D:\src\LightGBM.Net\LightGBMNet.Test\BoosterTest.cs:line 66
Result Message:	System.Exception : CommonParameters differ from those used to create training set

**Comment by mjmckp** [comment] 2020-07-08 00:10
Thanks for taking a look, @guolinke 

I have uncommented and fixed up the disabled `ResetTrainingData` test, please pull and try again.

To run the tests from the console, the command line is
```
"C:\Program Files\dotnet\dotnet.exe" vstest --Tests:Create C:\LightGBM.Net\LightGBMNet.Test\bin\x64\Debug\netcoreapp2.1\LightGBMNet.Test.dll --logger:trx;LogFileName=output.txt
```
for the `Create` test, and
```
"C:\Program Files\dotnet\dotnet.exe" vstest --Tests:ResetTrainingData C:\LightGBM.Net\LightGBMNet.Test\bin\x64\Debug\netcoreapp2.1\LightGBMNet.Test.dll --logger:trx;LogFileName=output.txt
```
for the `ResetTrainingData` test.  You may need to alter the path to `LightGBMNet.Test.dll`, depending on where it is located on your PC.

**Comment by StrikerRUS** [comment] 2020-07-20 16:48
@guolinke If I'm not mistaken, this issue was resolved in #3238, right?

**Comment by guolinke** [comment] 2020-07-21 01:39
@StrikerRUS I think it fixed #3151 , not this.

**Comment by guolinke** [comment] 2020-07-21 08:17
ping @mjmckp to confirm.

**Comment by StrikerRUS** [comment] 2020-07-21 12:20
OK, seems I was just confused by 
> We will resolve this with a pull request together with the problem in #3152.

in https://github.com/microsoft/LightGBM/issues/3151#issuecomment-660133543

**Comment by guolinke** [comment] 2020-07-21 12:33
also ping @shiyu1994 to confirm.

**Comment by mjmckp** [comment] 2020-07-21 20:51
@guolinke That's correct, this is a different and currently unresolved issue,

**Comment by shiyu1994** [comment] 2020-07-23 03:15
@mjmckp In the ResetTrainingData test, `dataSet2` is created by calling `new Dataset(dataSet, dataSet.NumRows / 2);`. And the Dataset constructor calls the LightGBM interface `LGBM_DatasetCreateByReference`. 

However, note that this does not really create a new `dataSet2` with the first half rows of `dataSet`. It only creates an empty framework of dataset with half the size, since the `LGBM_DatasetCreateByReference` only calls `CreateValid` method. This does not actually push the feature values into `dataSet2`. And it does not finish the construction of Dataset. In other words, the feature values and feature iterators of this newly created dataset is undefined. And this causes the error in this Issue.

> https://github.com/microsoft/LightGBM/blob/952e23a0093e68cde6453c7ac2f4a818b5892c81/src/c_api.cpp#L931-L940

There are some sparse feature iterators in the newly created dataset which is not well initialized (the `FinishLoad()` method is not called). Thus when the following method is called

> https://github.com/microsoft/LightGBM/blob/952e23a0093e68cde6453c7ac2f4a818b5892c81/src/io/sparse_bin.hpp#L640-L650

the `vals_` will be of size 0 and `i_delta_` will be of value -1, which causes the index out of bound error.

To fix this, I suggest to call `LGBM_DatasetPushRows` in the Dataset constructor used to create `dataSet2` in LightGBM.Net, to push the first half rows of `dataSet` into `dataSet2`. Simply calls `LGBM_DatasetCreateByReference` does not create a meaningful dataset. 

As you mentioned, the test passes in a previous version of LightGBM. This is perhaps because earlier version of LightGBM did not process the training dataset (accessing the feature iterators to get feature values) before training. But in the latest version, the booster has to do some initialization work by accessing the feature iterators. 

If you have any suggestion for these C_APIs, I'm also willing to help.

**Closed** 2020-10-05 18:44 UTC
