### ISSUE TITLE
Question: behavior of `Booster.predict()` with wrong number of columns

### ISSUE THREAD

**Issue by jsh9** [microsoft/LightGBM#2366] opened 2019-08-29 20:37 UTC
I have a question about the behavior of `Booster.predict()`, when the input data has incorrect number of columns.

For example, a model `mdl` is trained on `X_train` which has 10 features, and both operations below raised no exception:
```python
y_pred_1 = mdl.predict(X_with_only_5_columns)   # success
y_pred_2 = mdl.predict(X_with_20_columns)  # success
```

Could someone explain the behavior in each of the two cases above?

**Comment by StrikerRUS** [comment] 2019-08-29 23:58
@jsh9 

Unfortunately, this is a bug and duplicate of #812. So, closing this issue as duplicate.

**Closed by StrikerRUS** 2019-08-29 23:58 UTC
Labels: bug, duplicate
