### ISSUE TITLE
any TODO for supporting train lightgbm make use of multi-GPU

### ISSUE THREAD

**Issue by wuyunhua** [microsoft/LightGBM#2202] opened 2019-05-30 10:48 UTC
does community has any feature for supporting make use of all GPUs on machine?

**Comment by Laurae2** [comment] 2019-05-30 10:53
ping @huanzhang12

**Comment by StrikerRUS** [comment] 2019-05-30 10:59
Closing as a duplicate of #620.

**Closed by StrikerRUS** 2019-05-30 10:59 UTC
