### ISSUE TITLE
MinGW fails with access violation writing error

### ISSUE THREAD

**Issue by StrikerRUS** [microsoft/LightGBM#1818] opened 2018-11-02 18:48 UTC
Just moving my [comment](https://github.com/Microsoft/LightGBM/pull/1660#issue-214413278) from old PR to a separate issue for the discussion and easier searching for users.

While working on that PR, I found weird bug under MinGW. The same symptoms were described in #1475. When I tried to run **all** examples by `pytest %APPVEYOR_BUILD_FOLDER%\tests` instead of `pytest %APPVEYOR_BUILD_FOLDER%\tests\python_package_test`, two C_API tests were passed succesfully, but all other tests failed with `OSError: exception: access violation writing 0xFFFFFFFF93400000`. At present this bug is avoided by running only Python tests (without C_API). I suppose, it's somehow connected to that the same `lib_lightgbm.dll` is loaded twice from different places (from installation directory for C_API tests and from python-package directory for Python tests). 

## Environment info

Operating System: Windows

Compiler: any MinGW-w64

## Error message

```
E       OSError: exception: access violation writing 0xFFFFFFFF93160000
```

Full log: https://ci.appveyor.com/project/guolinke/lightgbm/builds/20010549/job/ewn044xw9dja8g9y

## Steps to reproduce

1. Modify `.appveyor.yml` file:
```diff
test_script:
- - pytest %APPVEYOR_BUILD_FOLDER%\tests\python_package_test
+ - pytest %APPVEYOR_BUILD_FOLDER%\tests
```

**Comment by guolinke** [comment] 2018-11-06 02:56
@StrikerRUS I am not sure about the root cause, maybe some build flags for mingw are wrong ?

**Comment by StrikerRUS** [comment] 2018-11-06 10:03
@guolinke To be honest, I'm not familiar with this, I remember only I added `static` linking to eliminate [confusion](https://github.com/dmlc/xgboost/issues/977) with `conda`'s libraries:

https://github.com/Microsoft/LightGBM/blob/a0efb07bb8ef9d8a80f246a933c623e253a8a0a3/CMakeLists.txt#L119-L121

**Comment by StrikerRUS** [comment] 2018-11-08 16:50
All tests are passed when `-O3` flag is removed.
```diff
diff --git a/.appveyor.yml b/.appveyor.yml
index 6ea6da0..6f8daf2 100644
--- a/.appveyor.yml
+++ b/.appveyor.yml
@@ -42,7 +42,7 @@ build_script:
     python setup.py install)

 test_script:
-  - pytest %APPVEYOR_BUILD_FOLDER%\tests\python_package_test
+  - pytest %APPVEYOR_BUILD_FOLDER%\tests
   - cd %APPVEYOR_BUILD_FOLDER%\examples\python-guide
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 057302b..1540cd4 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -113,7 +113,7 @@ if(USE_HDFS)
 endif(USE_HDFS)

 if(UNIX OR MINGW OR CYGWIN)
-    SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11 -pthread -O3 -Wextra -Wall -Wno-ignored-attributes -Wno-unknown-pragmas -Wno-return-type")
+    SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11 -pthread -Wextra -Wall -Wno-ignored-attributes -Wno-unknown-pragmas -Wno-return-type")
 endif()
```

Log: https://ci.appveyor.com/project/guolinke/lightgbm/builds/20151191/job/5gi6ebjpevehk06n

**Comment by StrikerRUS** [comment] 2018-11-09 15:07
Linking #1588.

**Comment by StrikerRUS** [comment] 2018-11-10 21:49
The flag which causes a crash is `-fipa-reference-addressable` (https://gcc.gnu.org/onlinedocs/gcc/Optimize-Options.html).

**Comment by guolinke** [comment] 2018-11-13 05:00
Thanks @StrikerRUS so much. is this problem solved ?

**Comment by StrikerRUS** [comment] 2018-11-13 09:52
@guolinke Happy to help!

Unfortunately, I can't find any information about the `-fipa-reference-addressable` flag, except official one-line description. In additional, I'm not sure, but it seems that there is no way to specify **O3 except one** flag...
My intuition is that we should find error-producing variable(s) and protect them from the optimization.
Maybe you know what can be done further?

**Comment by StrikerRUS** [comment] 2018-12-28 05:53
@guolinke Yep! And it seems to me that it can be solved only by removing `O*` flag...
I think that it's not a critical problem which should be in our focus, but who knows, maybe sometime in the future we'll come to the solution.

**Comment by StrikerRUS** [comment] 2019-08-01 16:24
@guolinke It seems to me that it's more a bug than a feature request, so reopening this and removing from #2302.

**Comment by guolinke** [comment] 2022-03-01 12:53
@StrikerRUS is this still happening?

**Comment by jameslamb** [comment] 2022-03-01 18:31
The last time we received a report that _might_ be related was December 2021 (#4192), but that person never responded.

I don't remember seeing it in LightGBM's CI in the last year. I think we could probably close this issue, but will let @StrikerRUS decide.

**Comment by jameslamb** [comment] 2023-02-01 02:26
I don't recall seeing this in the last year, and the project still has pretty good CI coverage for Windows + MinGW across CLI, Python, and R jobs.

I'm going to close this.

**Closed by jameslamb** 2023-02-01 02:26 UTC
Labels: help wanted
