### ISSUE TITLE
There seems to be a bug when the data exceeds 3 billion

### ISSUE THREAD

**Issue by li26338710** [microsoft/LightGBM#5340] opened 2022-06-30 13:36 UTC
When training about >3 billion rows (limited by int32?)
If so, how should this problem be avoided?

**Comment by StrikerRUS** [comment] 2022-07-03 14:16
You are right, there is an ongoing work on this problem: #4809.

Duplicate of #4804.

**Closed by StrikerRUS** 2022-07-03 14:16 UTC

**Comment by jameslamb** [comment] 2022-07-05 17:24
@li26338710 in the future, please don't edit posts here to remove all of your original comments or the title.

I just restored the title and content of this issue. It's important that we be able to look back at these issues and understand what the conversation was about. With the title changed to `[closed] duplicate` and all of the issue body removed, it's hard to understand what was asked and how @StrikerRUS 's response was related to it.
