### ISSUE TITLE
LightGBM dump_model() conflicts with matplotlib 3.1.x

### ISSUE THREAD

**Issue by AlexeyKupershtokh** [microsoft/LightGBM#2399] opened 2019-09-11 10:39 UTC
## Environment info

Operating System: Linux Mint 18

CPU/GPU model: AMD Ryzen 2600, Asus GTX 1060 6GB

C++/Python/R version: python 3.7.3

LightGBM version or commit hash: 2.2.0

## Error message

```
Traceback (most recent call last):
  File "1.py", line 24, in <module>
    print(clf.booster_.dump_model()['name'])
  File "/home/wicked/anaconda3/lib/python3.7/site-packages/lightgbm/basic.py", line 2052, in dump_model
    return json.loads(string_buffer.value.decode())
  File "/home/wicked/anaconda3/lib/python3.7/site-packages/simplejson/__init__.py", line 518, in loads
    return _default_decoder.decode(s)
  File "/home/wicked/anaconda3/lib/python3.7/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/home/wicked/anaconda3/lib/python3.7/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 24 column 14 (char 534)
```

## Reproducible examples
```sh
pip install lightgbm catboost
```

```python
import matplotlib.pyplot as plt
import lightgbm
from catboost.datasets import titanic
train, test = titanic()

target = train['Survived']
train.drop('Survived', inplace=True, axis=1)

train.drop(['Name', 'Sex', 'Ticket', 'Cabin', 'Embarked'], inplace=True, axis=1)
test.drop(['Name', 'Sex', 'Ticket', 'Cabin', 'Embarked'], inplace=True, axis=1)

clf = lightgbm.LGBMClassifier()

print(1)
clf.fit(train, target)
print(clf.booster_.dump_model()['name'])
print(2)
clf.fit(train, target)
print(clf.booster_.dump_model()['name'])
print(3)
plt.savefig('1.png')
print(4)
clf.fit(train, target)
print(clf.booster_.dump_model()['name'])
print(5)
```

## Steps to reproduce

1. run `pip install matplotlib==3.0.3`
2. run the example
3. observe
```
1
tree
2
tree
3
4
tree
5
```
4. run `pip install matplotlib==3.1.1`
5. run the example again
6. observe
```
1
tree
2
tree
3
QApplication: invalid style override passed, ignoring it.
4
Traceback (most recent call last):
  File "1.py", line 24, in <module>
    print(clf.booster_.dump_model()['name'])
  File "/home/wicked/anaconda3/lib/python3.7/site-packages/lightgbm/basic.py", line 2052, in dump_model
    return json.loads(string_buffer.value.decode())
  File "/home/wicked/anaconda3/lib/python3.7/site-packages/simplejson/__init__.py", line 518, in loads
    return _default_decoder.decode(s)
  File "/home/wicked/anaconda3/lib/python3.7/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/home/wicked/anaconda3/lib/python3.7/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 24 column 14 (char 534)
```

## Explanation

I don't quite understand what's going on, but I tracked down that the buffer `string_buffer.value.decode()` inside `lightgbm.basic.Booster.dump_model` contains such json:
```
{"name":"tree",
... 22 valid json lines here ...
"split_gain":nan,
```

**Comment by StrikerRUS** [comment] 2019-09-11 10:52
@AlexeyKupershtokh Thanks for reporting this! That error should be fixed in the latest `master`, refer to #2303. Can you check it please?

**Comment by AlexeyKupershtokh** [comment] 2019-09-11 11:06
No it's not fixed at least for me.

The error is a bit different 

though:
```
% python 1.py
LightGBM version: 2.2.4
1
tree
2
tree
3
QApplication: invalid style override passed, ignoring it.
4


Traceback (most recent call last):
  File "1.py", line 25, in <module>
    print(clf.booster_.dump_model()['name'])
  File "/home/wicked/anaconda3/lib/python3.7/site-packages/lightgbm/basic.py", line 2321, in dump_model
    ret = json.loads(string_buffer.value.decode())
  File "/home/wicked/anaconda3/lib/python3.7/
[23167.txt](https://github.com/microsoft/LightGBM/files/3600443/23167.txt)
site-packages/simplejson/__init__.py", line 518, in loads
    return _default_decoder.decode(s)
  File "/home/wicked/anaconda3/lib/python3.7/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/home/wicked/anaconda3/lib/python3.7/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 44 column 18 (char 985)
```

Attaching the dumped file for you.

**Comment by StrikerRUS** [comment] 2019-09-11 21:10
Unfortunately, I cannot reproduce the error.

```
import matplotlib.pyplot as plt
import lightgbm
from catboost.datasets import titanic

from lightgbm import __version__ as lgb_ver
from matplotlib import __version__ as mpl_ver
from catboost import __version__ as cbs_ver

print("LightGBM: {}".format(lgb_ver))
print("matplotlib: {}".format(mpl_ver))
print("CatBoost: {}".format(cbs_ver))

train, test = titanic()

target = train['Survived']
train.drop('Survived', inplace=True, axis=1)

train.drop(['Name', 'Sex', 'Ticket', 'Cabin', 'Embarked'], inplace=True, axis=1)
test.drop(['Name', 'Sex', 'Ticket', 'Cabin', 'Embarked'], inplace=True, axis=1)

clf = lightgbm.LGBMClassifier()

print(1)
clf.fit(train, target)
print(clf.booster_.dump_model()['name'])
print(2)
clf.fit(train, target)
print(clf.booster_.dump_model()['name'])
print(3)
plt.savefig('1.png')
print(4)
clf.fit(train, target)
print(clf.booster_.dump_model()['name'])
print(5)
```

```
LightGBM: 2.2.4
matplotlib: 3.1.1
CatBoost: 0.17
1
tree
2
tree
3
4
tree
5
```

Attaching the dumped model in file to compare.
[model.txt](https://github.com/microsoft/LightGBM/files/3602750/model.txt)

**Closed** 2019-09-23 12:26 UTC
