### ISSUE TITLE
R jobs fail on Windows without any logs

### ISSUE THREAD

**Issue by StrikerRUS** [microsoft/LightGBM#4050] opened 2021-03-05 14:22 UTC
The most recent `master` build fails with the following error:

```
Running R CMD check
R CMD check build logs:
Get-Content: D:\a\LightGBM\LightGBM\.ci\test_r_package_windows.ps1:164
Line |
 164 |    Get-Content -Path "$INSTALL_LOG_FILE_NAME"
     |    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Cannot find path 'C:\tmp-r-cmd-check\lightgbm.Rcheck\00install.out' because it does not exist.

Error: Process completed with exit code 1.
```

I re-run several times, but the error is still occurs.

Quite weird because there is no any error reported during infrastructure installation 😕 .

Full logs: https://github.com/microsoft/LightGBM/runs/2039644549.

cc @jameslamb

**Comment by jameslamb** [comment] 2021-03-05 16:55
:scream: I'm so confused. Maybe something with how we carefully redirect output (https://github.com/microsoft/LightGBM/blob/3a5e3c001f7a571eec375d021d12ccd37353a60c/.ci/test_r_package_windows.ps1#L23) is now incompatible with something in those images. Like maybe the version of powershell was upgraded or something?

I won't be able to look at this for a few hours, apologies.

**Comment by StrikerRUS** [comment] 2021-03-05 19:47
> Maybe something with how we carefully redirect output 

Hmmm, very likely. I didn't thought about it!

**Comment by jameslamb** [comment] 2021-03-06 21:27
It seems that a more recent build of the R jobs (9 hours ago, for #1767) passed, so maybe this was something temporary?

https://github.com/microsoft/LightGBM/actions/runs/627184704

I just restarted the builds on `master` (https://github.com/microsoft/LightGBM/actions/runs/624383739), let's see what happens.

**Comment by jameslamb** [comment] 2021-03-06 22:00
This build just passed on `master`, so maybe it is something temporary? https://github.com/microsoft/LightGBM/runs/2047939220

I'll at least remove the "blocking" label from this and #4049 since it seems the problem was temporary, but we shouldn't close it yet without figuring out the root cause.

**Comment by StrikerRUS** [comment] 2021-03-07 18:59
> but we shouldn't close it yet without figuring out the root cause.

I guess it will be difficult because we have no reproducible case and after re-running failed job old logs were overwritten.

**Comment by StrikerRUS** [comment] 2021-03-27 22:35
Just a remark: I haven't seen this error for a while. Maybe it is enough to look through `Run-R-Code-Redirect-Stderr` source code for possible bugs and close this issue in case of no findings for now?

**Comment by jameslamb** [comment] 2021-03-28 04:14
I also have not! I think it's ok to close for now. I can't see anything problematic in `Run-R-Code-Redirect-Stderr`.

**Closed by jameslamb** 2021-03-28 04:14 UTC
Labels: maintenance, r-package
