### ISSUE TITLE
Suppress LightGBM Warning

### ISSUE THREAD

**Issue by startakovsky** [Microsoft/LightGBM#1157] opened 2017-12-30 01:46 UTC
The following line is replicated throughout the training for each iteration and it doesn't seem to be generating through Python's standard (warnings)[https://docs.python.org/3/library/warnings.html] module:

`[LightGBM] [Warning] No further splits with positive gain, best gain: -inf`

How can I suppress this warning? It is generated [here](https://github.com/Microsoft/LightGBM/blob/92f2a570efbd9af898cbb4bf42dec1a595c6e9d7/src/treelearner/serial_tree_learner.cpp#L191). Also, if possible, can you tell me the meaning of this warning?

**Comment by guolinke** [comment] 2017-12-30 02:55
it means:
1. the num_leaves is too large, you can set it to a smaller value
2. the min_data is too large
3. your data is hard to fit

**Comment by startakovsky** [comment] 2017-12-30 19:14
thanks, how do you suppress these warnings and keep reporting the validation metrics using `verbose_eval`?

**Comment by guolinke** [comment] 2017-12-31 01:28
set verbose=-1

**Comment by guolinke** [comment] 2018-06-07 00:44
for sklearn interface, you can set `verbose=-1` when defining the model (not in `fit`).
for lgb.train interface, you can set `verbose=-1` in `param` dict.

**Comment by prashant-kikani** [comment] 2018-06-23 05:21
@guolinke what abour lgb.cv ? Can I suppress this warning in lgb.cv?

**Comment by prashant-kikani** [comment] 2018-06-23 05:46
For cv, no parameter like "verbose". "verbose_eval" is there. But setting
it to -1 doesn't solve the problem.

**Comment by guolinke** [comment] 2018-06-23 07:00
set it in param dict, not the function arguments.

**Comment by hoihui** [comment] 2018-06-28 13:19
setting 'verbose' or 'verbosity' to -1 in the param dict solves this problem for lgb.train, 
but it does not help for lgb.cv, or for lgb.train with continued training (i.e. with init_model)

**Comment by guolinke** [comment] 2018-06-28 14:49
ping @StrikerRUS

**Comment by StrikerRUS** [comment] 2018-06-28 18:52
@guolinke I confirm that with `init_model` setting `verbose=-1` doesn't work. However, in `cv` `verbose=-1` works well for me.

**Comment by guolinke** [comment] 2018-06-29 07:47
@StrikerRUS 
what logs are shown ? 
Including the training information?

**Comment by StrikerRUS** [comment] 2018-06-29 09:52
@guolinke 
>what logs are shown ?

Only warnings:
```
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
```

**Comment by goldentom42** [comment] 2018-07-02 10:06
Hi there, I copy the content of issue #1486 as requested by @StrikerRUS 

## Environment info
Operating System: Linux and windows (can't test on Apple)
C++/Python/R version: latest version (I believe Kaggle uses the latest master branch), occurs also on 2.1.0

## Reproducible examples
https://www.kaggle.com/ogrellier/lighgbm-with-selected-features

The problem only occurs **with lgb.train** (LGBClassifier does not exhibit the same issue) and only if **eval_sets** argument is provided.

![image](https://user-images.githubusercontent.com/17214417/42148603-32237e1e-7dd3-11e8-984d-46f277542d6a.png)

Let me know if you need any further info.
Thanks, Olivier

**Comment by goldentom42** [comment] 2018-07-02 10:07
Just to recap : 
 - Sklearn API works correctly
 - lgb.train has the problem if an eval_sets is provided whatever verbose, verbosity or verbose_eval

Hope this helps.

**Comment by pseudotensor** [comment] 2018-07-19 08:07
```
[LightGBM] [Warning] boosting is set=gbdt, boosting_type=gbdt will be ignored. Current value: boosting=gbdt
[LightGBM] [Warning] num_threads is set=4, nthread=-1 will be ignored. Current value: num_threads=4
```

With the sklearn API I still get during fit the above types of messages even of False is passed to fit() and verbose=-1 passed as dict into the initial class part of a dict.

**Comment by StrikerRUS** [comment] 2018-07-19 10:01
@pseudotensor These parameters are regular arguments of the constructor, you should use them instead of aliases in params.

**Comment by pseudotensor** [comment] 2018-07-19 15:29
yes thanks, just bit odd these main sklearn ones are listed as aliases

**Comment by StrikerRUS** [comment] 2018-08-30 09:57
I will really appreciate if everyone here will test the fix proposed in #1628 (`verbose` branch) and report here whether it helped in your case.

@goldentom42 Speaking personally about your case, passing `params={'verbose': -1}` in `Dataset` constructor should help even without the fix.

**Comment by goldentom42** [comment] 2018-08-30 15:44
Sorry but I'm not sure I understand your statement:  I should remove silent=True in the lgb.Dataset() call and set verbose: - 1 when calling lgb.train ?

**Comment by StrikerRUS** [comment] 2018-08-30 16:04
@goldentom42 Please see the example:
```
lgb_train = lgb.Dataset(X_train, y_train, params={'verbose': -1}, free_raw_data=False)
lgb_eval = lgb.Dataset(X_test, y_test, params={'verbose': -1}, free_raw_data=False)
gbm = lgb.train({'verbose': -1}, lgb_train,
                valid_sets=lgb_eval,
                verbose_eval=False)
```
`verbose=-1` in both Dataset constructor and `train` function.

**Comment by goldentom42** [comment] 2018-09-03 06:53
Hi @StrikerRUS, tested LightGBM on Kaggle  (they would normally have the latest version) and I don't see the warnings anymore with verbose : -1 in params.

On LightGBM 2.1.2, setting verbose to -1 in both Dataset and lightgbm params make warnings disappear.

Hope this helps.

**Comment by StrikerRUS** [comment] 2018-09-06 11:33
@goldentom42 Thanks for your reply! It seems to be that Kaggle uses the latest available release at PyPI, not the `master` branch:
https://github.com/Kaggle/docker-python/blob/cd1e6ac7d076775af2a5bfbcb65bfd98ea6629de/Dockerfile#L78

We are going to merge the fix into the `master` branch and close this issue. So, the latest code should work fine with either `silent=True` argument, or `'verbose': -1` parameter.
However, feel free to report any cases which left uncovered by the fix.

**Closed** 2018-09-06 11:35 UTC
Labels: bug

**Comment by joseortiz3** [comment] 2018-10-24 01:46
I still get
`[LightGBM] [Warning] num_threads is set=1, n_jobs=-1 will be ignored. Current value: num_threads=1`

**Comment by guolinke** [comment] 2018-10-24 03:31
@joseortiz3 We use alphabet order to override the parameters, therefore, num_therads will override n_jobs

**Comment by saksim** [comment] 2018-11-30 06:06
thanks for the message in this issue.

In a word, Could we understand it as the model would be run OK although such message printed out.
