### ISSUE TITLE
crash when data size exceeds int32

### ISSUE THREAD

**Issue by SiNZeRo** [microsoft/LightGBM#5705] opened 2023-02-09 10:45 UTC
maybe related to this code:

https://github.com/microsoft/LightGBM/blob/4f47547c88cc72de4b8f04de8de4e2b79a9240e7/src/io/cuda/cuda_row_data.cpp#L326

**Comment by jameslamb** [comment] 2023-02-09 15:07
Thanks for using LightGBM.

I've updated the link in your question to one that's anchored to a specific commit, so even if that file you've linked to is altered, anyone reading this in the future will know what line you meant. If you don't know how to do that, see https://docs.github.com/en/repositories/working-with-files/using-files/getting-permanent-links-to-files#press-y-to-permalink-to-a-file-in-a-specific-commit.

Typically a report like "this crashed" without any other details is very difficult for us to investigate. Since you didn't provide any details like a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example), I'm going to interpret this as a question.... "does training with `device_type=cuda` support using training data with more than `max(int32)` (2,147,483,647) rows"?

I SUSPECT that the answer is "no", given that even CPU-used LightGBM does not support more than int32 rows in the input data: #5454 .

@guolinke or @shiyu1994 can you please comment?

**Comment by SiNZeRo** [comment] 2023-02-09 16:22
> Thanks for using LightGBM.
> 
> I've updated the link in your question to one that's anchored to a specific commit, so even if that file you've linked to is altered, anyone reading this in the future will know what line you meant. If you don't know how to do that, see https://docs.github.com/en/repositories/working-with-files/using-files/getting-permanent-links-to-files#press-y-to-permalink-to-a-file-in-a-specific-commit.
> 
> Typically a report like "this crashed" without any other details is very difficult for us to investigate. Since you didn't provide any details like a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example), I'm going to interpret this as a question.... "does training with `device_type=cuda` support using training data with more than `max(int32)` (2,147,483,647) rows"?
> 
> I SUSPECT that the answer is "no", given that even CPU-based LightGBM does not support more than int32 rows in the input data: #5454 .
> 
> @guolinke or @shiyu1994 can you please comment?

thanks for the updates.

sorry for misleading you, actually datasize means num_rows * num_feats. 

somewhat related to this pr: https://github.com/microsoft/LightGBM/pull/5167

**Comment by jameslamb** [comment] 2023-02-11 16:51
closed via #5706

**Comment by jameslamb** [comment] 2023-02-11 16:51
thanks for the help @SiNZeRo !

**Closed by jameslamb** 2023-02-11 16:51 UTC
Labels: question
