### ISSUE TITLE
[ci] Random failure with Dask test

### ISSUE THREAD

**Issue by shiyu1994** [microsoft/LightGBM#6036] opened 2023-08-13 14:51 UTC
## Description
Random failure is observed with the dask test.
https://dev.azure.com/lightgbm-ci/lightgbm-ci/_build/results?buildId=15027&view=logs&j=c28dceab-947a-5848-c21f-eef3695e5f11&t=fa158246-17e2-53d4-5936-86070edbaacf

**Comment by shiyu1994** [comment] 2023-08-13 14:53
```
023-08-11T20:09:32.9098927Z ============================= test session starts ==============================
2023-08-11T20:09:32.9100400Z platform linux -- Python 3.9.17, pytest-7.4.0, pluggy-1.2.0
2023-08-11T20:09:32.9100967Z rootdir: /__w/1/s
2023-08-11T20:09:32.9101282Z collected 930 items
2023-08-11T20:09:32.9101420Z 
2023-08-11T20:09:33.0819004Z tests/c_api_test/test_.py ..                                             [  0%]
2023-08-11T20:09:33.4328663Z tests/python_package_test/test_basic.py ................................ [  3%]
2023-08-11T20:09:33.5676560Z ............................................                             [  8%]
2023-08-11T20:09:33.5842195Z tests/python_package_test/test_callback.py ............                  [  9%]
2023-08-11T20:09:39.2660733Z tests/python_package_test/test_consistency.py ......                     [ 10%]
2023-08-11T20:10:03.3061506Z tests/python_package_test/test_dask.py ................................. [ 13%]
2023-08-11T20:10:43.3315530Z ........................................................................ [ 21%]
2023-08-11T20:11:31.4018792Z ........................................................................ [ 29%]
2023-08-11T20:13:15.0658584Z .................s...............s...............s...............s...... [ 37%]
2023-08-11T20:13:57.1135894Z .............................................s............ssss.......... [ 44%]
2023-08-11T20:14:08.7504054Z ...........sF......................s.........                            [ 49%]
2023-08-11T20:14:08.7516043Z tests/python_package_test/test_dual.py s                                 [ 49%]
2023-08-11T20:14:20.4214125Z tests/python_package_test/test_engine.py ............................s.. [ 53%]
2023-08-11T20:14:59.1392583Z .s...................................................................... [ 60%]
2023-08-11T20:15:00.7252119Z .............................                                            [ 63%]
2023-08-11T20:15:02.0265894Z tests/python_package_test/test_plotting.py ......s.......                [ 65%]
2023-08-11T20:15:06.4434598Z tests/python_package_test/test_sklearn.py .............................. [ 68%]
2023-08-11T20:15:17.0315130Z ........x..................................................x............ [ 76%]
2023-08-11T20:15:24.6952225Z ................................................s.....s.....s.....s..... [ 84%]
2023-08-11T20:15:26.7956485Z s.....s.....s.....s.....s.....s.....s.....s.....s.....s.....s.....s..... [ 91%]
2023-08-11T20:15:28.4556591Z s.....s.....s.....s.....s.....s.....s.....s.....s.....s.....s.....s..... [ 99%]
2023-08-11T20:15:28.4557433Z                                                                          [ 99%]
2023-08-11T20:15:28.4890977Z tests/python_package_test/test_utilities.py ...                          [100%]
2023-08-11T20:15:28.4891732Z 
2023-08-11T20:15:28.4892161Z =================================== FAILURES ===================================
2023-08-11T20:15:28.4893374Z _______________ test_init_score[dataframe-binary-classification] _______________
2023-08-11T20:15:28.4893775Z 
2023-08-11T20:15:28.4903712Z task = 'binary-classification', output = 'dataframe'
2023-08-11T20:15:28.4915492Z cluster = LocalCluster(4f1db814, 'tcp://127.0.0.1:37197', workers=2, threads=4, memory=7.77 GiB)
2023-08-11T20:15:28.4916229Z 
2023-08-11T20:15:28.4916805Z     @pytest.mark.parametrize('task', tasks)
2023-08-11T20:15:28.4919017Z     @pytest.mark.parametrize('output', data_output)
2023-08-11T20:15:28.4919626Z     def test_init_score(task, output, cluster):
2023-08-11T20:15:28.4920341Z         if task == 'ranking' and output == 'scipy_csr_matrix':
2023-08-11T20:15:28.4921176Z             pytest.skip('LGBMRanker is not currently tested on sparse matrices')
2023-08-11T20:15:28.4921563Z     
2023-08-11T20:15:28.4921839Z         with Client(cluster) as client:
2023-08-11T20:15:28.4922253Z             _, _, _, _, dX, dy, dw, dg = _create_data(
2023-08-11T20:15:28.4922560Z                 objective=task,
2023-08-11T20:15:28.4922802Z                 output=output,
2023-08-11T20:15:28.4923089Z                 group=None
2023-08-11T20:15:28.4923400Z             )
2023-08-11T20:15:28.4923614Z     
2023-08-11T20:15:28.4923849Z             model_factory = task_to_dask_factory[task]
2023-08-11T20:15:28.4924168Z     
2023-08-11T20:15:28.4924431Z             params = {
2023-08-11T20:15:28.4924800Z                 'n_estimators': 1,
2023-08-11T20:15:28.4925095Z                 'num_leaves': 2,
2023-08-11T20:15:28.4925443Z                 'time_out': 5
2023-08-11T20:15:28.4925658Z             }
2023-08-11T20:15:28.4925895Z             init_score = random.random()
2023-08-11T20:15:28.4926423Z             size_factor = 1
2023-08-11T20:15:28.4926972Z             if task == 'multiclass-classification':
2023-08-11T20:15:28.4927377Z                 size_factor = 3  # number of classes
2023-08-11T20:15:28.4927631Z     
2023-08-11T20:15:28.4928014Z             if output.startswith('dataframe'):
2023-08-11T20:15:28.4928337Z                 init_scores = dy.map_partitions(lambda x: pd.DataFrame([[init_score] * size_factor] * x.size))
2023-08-11T20:15:28.4928624Z             else:
2023-08-11T20:15:28.4928905Z                 init_scores = dy.map_blocks(lambda x: np.full((x.size, size_factor), init_score))
2023-08-11T20:15:28.4929204Z             model = model_factory(client=client, **params)
2023-08-11T20:15:28.4929528Z >           model.fit(dX, dy, sample_weight=dw, init_score=init_scores, group=dg)
2023-08-11T20:15:28.4929717Z 
2023-08-11T20:15:28.4930080Z tests/python_package_test/test_dask.py:1746: 
2023-08-11T20:15:28.4930356Z _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
2023-08-11T20:15:28.4930766Z /home/AzDevOps_azpcontainer/.local/lib/python3.9/site-packages/lightgbm/dask.py:1202: in fit
2023-08-11T20:15:28.4931049Z     self._lgb_dask_fit(
2023-08-11T20:15:28.4931512Z /home/AzDevOps_azpcontainer/.local/lib/python3.9/site-packages/lightgbm/dask.py:1082: in _lgb_dask_fit
2023-08-11T20:15:28.4931801Z     model = _train(
2023-08-11T20:15:28.4932216Z /home/AzDevOps_azpcontainer/.local/lib/python3.9/site-packages/lightgbm/dask.py:818: in _train
2023-08-11T20:15:28.4932522Z     results = client.gather(futures_classifiers)
2023-08-11T20:15:28.4932962Z /opt/miniforge/envs/test-env/lib/python3.9/site-packages/distributed/client.py:2404: in gather
2023-08-11T20:15:28.4933244Z     return self.sync(
2023-08-11T20:15:28.4933718Z /opt/miniforge/envs/test-env/lib/python3.9/site-packages/distributed/utils.py:359: in sync
2023-08-11T20:15:28.4933991Z     return sync(
2023-08-11T20:15:28.4934428Z /opt/miniforge/envs/test-env/lib/python3.9/site-packages/distributed/utils.py:426: in sync
2023-08-11T20:15:28.4934715Z     raise exc.with_traceback(tb)
2023-08-11T20:15:28.4935091Z /opt/miniforge/envs/test-env/lib/python3.9/site-packages/distributed/utils.py:399: in f
2023-08-11T20:15:28.4935361Z     result = yield future
2023-08-11T20:15:28.4935740Z /opt/miniforge/envs/test-env/lib/python3.9/site-packages/tornado/gen.py:767: in run
2023-08-11T20:15:28.4936013Z     value = future.result()
2023-08-11T20:15:28.4936457Z /opt/miniforge/envs/test-env/lib/python3.9/site-packages/distributed/client.py:2267: in _gather
2023-08-11T20:15:28.4936751Z     raise exception.with_traceback(traceback)
2023-08-11T20:15:28.4937298Z /home/AzDevOps_azpcontainer/.local/lib/python3.9/site-packages/lightgbm/dask.py:313: in _train_part
2023-08-11T20:15:28.4937578Z     model.fit(
2023-08-11T20:15:28.4938092Z /home/AzDevOps_azpcontainer/.local/lib/python3.9/site-packages/lightgbm/sklearn.py:1142: in fit
2023-08-11T20:15:28.4938362Z     super().fit(
2023-08-11T20:15:28.4938851Z /home/AzDevOps_azpcontainer/.local/lib/python3.9/site-packages/lightgbm/sklearn.py:842: in fit
2023-08-11T20:15:28.4939133Z     self._Booster = train(
2023-08-11T20:15:28.4939580Z /home/AzDevOps_azpcontainer/.local/lib/python3.9/site-packages/lightgbm/engine.py:255: in train
2023-08-11T20:15:28.4939886Z     booster = Booster(params=params, train_set=train_set)
2023-08-11T20:15:28.4940319Z /home/AzDevOps_azpcontainer/.local/lib/python3.9/site-packages/lightgbm/basic.py:3143: in __init__
2023-08-11T20:15:28.4940603Z     train_set.construct()
2023-08-11T20:15:28.4941039Z /home/AzDevOps_azpcontainer/.local/lib/python3.9/site-packages/lightgbm/basic.py:2257: in construct
2023-08-11T20:15:28.4941360Z     self._lazy_init(data=self.data, label=self.label, reference=None,
2023-08-11T20:15:28.4941798Z /home/AzDevOps_azpcontainer/.local/lib/python3.9/site-packages/lightgbm/basic.py:1903: in _lazy_init
2023-08-11T20:15:28.4942108Z     self.__init_from_np2d(data, params_str, ref_dataset)
2023-08-11T20:15:28.4942514Z /home/AzDevOps_azpcontainer/.local/lib/python3.9/site-packages/lightgbm/basic.py:2037: in __init_from_np2d
2023-08-11T20:15:28.4942892Z     _safe_call(_LIB.LGBM_DatasetCreateFromMat(
2023-08-11T20:15:28.4943248Z _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
2023-08-11T20:15:28.4943384Z 
2023-08-11T20:15:28.4943795Z >   raise LightGBMError(_LIB.LGBM_GetLastError().decode('utf-8'))
2023-08-11T20:15:28.4944128Z E   lightgbm.basic.LightGBMError: Socket recv error, Connection reset by peer (code: 104)
2023-08-11T20:15:28.4944363Z 
2023-08-11T20:15:28.4944836Z /home/AzDevOps_azpcontainer/.local/lib/python3.9/site-packages/lightgbm/basic.py:238: LightGBMError
```

**Comment by jameslamb** [comment] 2023-08-14 02:50
Thanks for taking the time to open this.

Just for my understanding... how is it different from this other open issue, #4074 ?

**Comment by jameslamb** [comment] 2023-09-07 18:54
@shiyu1994 could you please answer https://github.com/microsoft/LightGBM/issues/6036#issuecomment-1676595414?

Otherwise, I'm going to close this and mark it as a duplicate of #4074.

**Closed** 2023-09-08 16:01 UTC
Labels: bug, awaiting response, maintenance, dask
