### ISSUE TITLE
LGBM_BoosterLoadModelFromString failed on windows, but succeed in macos

### ISSUE THREAD

**Issue by SKTT1Ryze** [microsoft/LightGBM#5577] opened 2022-11-07 10:45 UTC
## Description
LGBM_BoosterLoadModelFromString c_api failed on windows, but succeed in macos.
Error msg in windows:
```
Model format error, expect a tree here. met shrinkage=0.1
```

## Env
lib_lightgbm.dll version: 3.3.3, windows x86_64

**Comment by jameslamb** [comment] 2022-11-07 15:19
@SKTT1Ryze thanks for using LightGBM!

I see you opened and then immediately closed this....what happened? It would be useful for others arriving at this issue from search engines to understand the cause of that error and how you got past it.

**Comment by SKTT1Ryze** [comment] 2022-11-08 14:45
In the windows platform, model file is dos format and only the unix format is understood by LightGBM.

> @SKTT1Ryze thanks for using LightGBM!
> 
> I see you opened and then immediately closed this....what happened? It would be useful for others arriving at this issue from search engines to understand the cause of that error and how you got past it.

**Comment by jameslamb** [comment] 2022-11-14 05:26
I see, I suspect you ran into the same issue as #5508.

Thanks for that explanation. In the future, if you post here and then close the discussion, please provide an explanation so that other people finding the conversation from search engines can learn from your experience.

**Closed by jameslamb** 2022-11-14 05:26 UTC
Labels: question
