### ISSUE TITLE
LightGBM predicts even with missing features

### ISSUE THREAD

**Issue by aakash-sahu** [microsoft/LightGBM#2396] opened 2019-09-10 15:23 UTC
A trained LightGBM model provides prediction on data frame with missing numerical features without producing any error. It does gives error when using categorical features. Looks like an issue. Or is it by design? XGBoost gives error if any column is missing in production.

## Environment info

Operating System: Linux
Processor: 'x86_64'
Python version: 3.6.8
LightGBM version: '2.2.3'

## Error message
**No error message when there should be one**

## Code example

```python
import lightgbm as lgb
import pandas as pd

#https://www.kaggle.com/wenruliu/adult-income-dataset
data = pd.read_csv('adult.csv' )

income_map = {'<=50K':0, '>50K':1}
data['income'] = data['income'].map(income_map)

categorical_cols = [col for col in data.columns if data[col].dtypes == 'O']
numeric_cols = [col for col in data.columns if data[col].dtypes != 'O'];numeric_cols.remove('income')
all_cols = categorical_cols + numeric_cols

#Convert object columns to categorical
for col in categorical_cols:
    data[col] = data[col].astype('category')
    
x_train = data[all_cols]
y_train = data['income']

params_lgb = {'objective': 'binary', 'random_state': 123, 'metric':'auc'}
clf_lgb = lgb.train(params_lgb, lgb.Dataset(x_train, label = y_train), num_boost_round=10)

#Checking feature names
print('Feature names in the model',clf_lgb.feature_name())

#Now predicting with only categorical columns
print('Prediction with using only categorical features  --none of numeric feature. Should ideally give error.....:')
print(clf_lgb.predict(x_train[categorical_cols]))

## Still getting Output - [0.09489228 0.13163263 0.15909012 ... 0.09489228 0.09489228 0.17614929]

#Now predicting with only numerical columns --none of categorical column
print('Prediction with using only numerical features  --none of catgorical feature. This gives error as below....:')
print(clf_lgb.predict(x_train[numeric_cols]))
```
```
Feature names in the model ['workclass', 'education', 'marital-status', 'occupation', 'relationship', 'race', 'gender', 'native-country', 'age', 'fnlwgt', 'educational-num', 'capital-gain', 'capital-loss', 'hours-per-week']
Prediction with using only categorical features  --none of numeric feature. Should ideally give error.....:
[0.09489228 0.13163263 0.15909012 ... 0.09489228 0.09489228 0.17614929]
Prediction with using only numerical features  --none of catgorical feature. This gives error as below....:
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-53-3c1115925657> in <module>
     33 #Now predicting with only numerical columns --none of categorical column
     34 print('Prediction with using only numerical features  --none of catgorical feature. This gives error as below....:')
---> 35 print(clf_lgb.predict(x_train[numeric_cols]))

~/.local/lib/python3.6/site-packages/lightgbm/basic.py in predict(self, data, num_iteration, raw_score, pred_leaf, pred_contrib, data_has_header, is_reshape, **kwargs)
   2201         return predictor.predict(data, num_iteration,
   2202                                  raw_score, pred_leaf, pred_contrib,
-> 2203                                  data_has_header, is_reshape)
   2204 
   2205     def refit(self, data, label, decay_rate=0.9, **kwargs):

~/.local/lib/python3.6/site-packages/lightgbm/basic.py in predict(self, data, num_iteration, raw_score, pred_leaf, pred_contrib, data_has_header, is_reshape)
    434         if isinstance(data, Dataset):
    435             raise TypeError("Cannot use Dataset instance for prediction, please use raw data instead")
--> 436         data = _data_from_pandas(data, None, None, self.pandas_categorical)[0]
    437         predict_type = C_API_PREDICT_NORMAL
    438         if raw_score:

~/.local/lib/python3.6/site-packages/lightgbm/basic.py in _data_from_pandas(data, feature_name, categorical_feature, pandas_categorical)
    252         else:
    253             if len(cat_cols) != len(pandas_categorical):
--> 254                 raise ValueError('train and valid dataset categorical_feature do not match.')
    255             for col, category in zip_(cat_cols, pandas_categorical):
    256                 if list(data[col].cat.categories) != list(category):

ValueError: train and valid dataset categorical_feature do not match.
```

### Adding XGBoost model for comparison
```python
#Training XGBooost for comparison
import xgboost as xgb
params_xgb = {'objective': 'binary:logistic', 'random_state': 123, 'eval-metric':'auc'}

print('Training Xgboost only on numerical columns as XGBoost does not takes categorical features directly.....')
clf_xgb = xgb.train(params_xgb, xgb.DMatrix(x_train[numeric_cols], label = y_train), num_boost_round=5)

print('XGBoost feature names:', clf_xgb.feature_names)

print('Predicting on only two numerical columns. This gives error...')
clf_xgb.predict(xgb.DMatrix(x_train[['age','capital-gain']]))
```
```
Training Xgboost only on numerical columns as XGBoost does not takes categorical features directly.....
/home/a653325/.local/lib/python3.6/site-packages/xgboost/core.py:587: FutureWarning: Series.base is deprecated and will be removed in a future version
  if getattr(data, 'base', None) is not None and \
/home/a653325/.local/lib/python3.6/site-packages/xgboost/core.py:588: FutureWarning: Series.base is deprecated and will be removed in a future version
  data.base is not None and isinstance(data, np.ndarray) \
XGBoost feature names: ['age', 'fnlwgt', 'educational-num', 'capital-gain', 'capital-loss', 'hours-per-week']
Predicting on only two numerical columns. This gives error...
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-49-e78f27aded4f> in <module>
      7 print('XGBoost feature names:', clf_xgb.feature_names)
      8 print('Predicting on only two numerical columns. This gives error...')
----> 9 clf_xgb.predict(xgb.DMatrix(x_train[['age','capital-gain']]))

~/.local/lib/python3.6/site-packages/xgboost/core.py in predict(self, data, output_margin, ntree_limit, pred_leaf, pred_contribs, approx_contribs, pred_interactions, validate_features)
   1282 
   1283         if validate_features:
-> 1284             self._validate_features(data)
   1285 
   1286         length = c_bst_ulong()

~/.local/lib/python3.6/site-packages/xgboost/core.py in _validate_features(self, data)
   1688 
   1689                 raise ValueError(msg.format(self.feature_names,
-> 1690                                             data.feature_names))
   1691 
   1692     def get_split_value_histogram(self, feature, fmap='', bins=None, as_pandas=True):

ValueError: feature_names mismatch: ['age', 'fnlwgt', 'educational-num', 'capital-gain', 'capital-loss', 'hours-per-week'] ['age', 'capital-gain']
expected fnlwgt, capital-loss, educational-num, hours-per-week in input data
```

**Comment by aakash-sahu** [comment] 2019-09-10 15:24
> prediction

**Comment by aakash-sahu** [comment] 2019-09-10 15:25
XGBoost gives error if any column is missing in **production**.

**Comment by aakash-sahu** [comment] 2019-09-10 15:25
XGBoost gives error if any column is missing in **prediction**

**Comment by guolinke** [comment] 2019-09-10 15:41
Thanks, i think we can Improve this for pandas data. Pandas provide the column names, so the names could be used to check the input data in predictions. 

But for numpy or other data types without column names, we cannot do this check.

**Comment by aakash-sahu** [comment] 2019-09-10 18:12
@guolinke - How about number of features between training and prediction? LGBM should match that irrespective of pandas/numpy. Though prediction with trained model is letting it through. On checking further, the number of features between train and predict doesn't matter at all. I can train with 2 and predict with 6 and vice versa. Check out the snippet:
```python
import lightgbm as lgb
import pandas as pd

#https://www.kaggle.com/wenruliu/adult-income-dataset
data = pd.read_csv('adult.csv' )

income_map = {'<=50K':0, '>50K':1}
data['income'] = data['income'].map(income_map)

#Training with only numeric features
numeric_cols = [col for col in data.columns if data[col].dtypes != 'O']
numeric_cols.remove('income')
reduced_numeric = ['age','capital-gain']
    
x_train_1 = data[numeric_cols].values
x_train_2 = data[reduced_numeric].values
y_train = data['income'].values

params_lgb = {'objective': 'binary', 'random_state': 123, 'metric':'auc'}
clf_lgb_1 = lgb.train(params_lgb, lgb.Dataset(x_train_1, label = y_train), num_boost_round=10)
clf_lgb_2 = lgb.train(params_lgb, lgb.Dataset(x_train_2, label = y_train), num_boost_round=10)

#Checking feature names
print('Feature names in model 1',clf_lgb_1.feature_name())
print('Feature names in model 2',clf_lgb_2.feature_name())

#Checking predictions
print(f'Trained with {clf_lgb_1.num_feature()} features.. predicting with only {len(reduced_numeric)} features..... :')
print(clf_lgb_1.predict(data[reduced_numeric].values))

print(f'Trained with {clf_lgb_2.num_feature()} features.. predicting with {len(numeric_cols)} features..... :')
print(clf_lgb_2.predict(data[numeric_cols].values))
```
#### Should at least give warning that number of features are not the same.
```
Feature names in model 1 ['Column_0', 'Column_1', 'Column_2', 'Column_3', 'Column_4', 'Column_5']
Feature names in model 2 ['Column_0', 'Column_1']
Trained with 6 features.. predicting with only 2 features..... :
[0.11735554 0.11684806 0.12100338 ... 0.11684806 0.09105766 0.11684806]
Trained with 2 features.. predicting with 6 features..... :
[0.69633532 0.73032613 0.70913087 ... 0.73032613 0.62543353 0.73032613]
```

**Comment by StrikerRUS** [comment] 2019-09-10 20:19
This is quite old enhancement request. We do have it in our **feature requests** list (the second item in *python package* section): #2302.

Feel free to contribute this feature!

Closing this issue as a duplicate of #812 to not split a discussion into small pieces in different places.

**Closed by StrikerRUS** 2019-09-10 20:19 UTC
