### ISSUE TITLE
Pandas 2.0 support

### ISSUE THREAD

**Issue by fermiyon** [microsoft/LightGBM#5823] opened 2023-04-07 19:35 UTC
## Summary

pandas 2.0 support

## Description
When trying to import lightgbm with pandas 2.0 installed, I got the error below. However, after downgrading to pandas 1.5.3, the problem was solved. 
AttributeError: module 'pandas.core.strings' has no attribute 'StringMethods'

**Comment by jameslamb** [comment] 2023-04-07 19:47
Thanks for your report, and sorry for the compatibility issue! I'm going to close this as a duplicate of the tracking issue we already have at #5739, and lock is so that others coming to the repo to report this don't split the conversation between multiple places.

We'll try to get a compatibility patch up soon.

**Closed by jameslamb** 2023-04-07 19:47 UTC
