### ISSUE TITLE
AMD OpenCL SDK download link is down

### ISSUE THREAD

**Issue by guolinke** [Microsoft/LightGBM#1342] opened 2018-04-26 15:14 UTC
@huanzhang12 the download link: https://developer.amd.com/amd-accelerated-parallel-processing-app-sdk/ is 404 now. That causes the build failed on check-the-docs and gpu tests.

**Comment by huanzhang12** [comment] 2018-05-04 07:00
Seems to be a problem with AMD. We need to find another mirror for AMD APP SDK.

**Comment by StrikerRUS** [comment] 2018-05-04 10:01
They say it's "temporary server problem":
https://community.amd.com/thread/227948
and provide link to the Dropbox:
https://community.amd.com/message/2859384#2859384

Also some mirror is provided here:
https://github.com/fireice-uk/xmr-stak/issues/1511#issuecomment-385120692

**Comment by StrikerRUS** [comment] 2018-05-18 22:03
Another possible solution is to move GPU tests to the Appveyor. Some links and paths could be fond [here](https://github.com/boostorg/compute/blob/master/.appveyor.yml).

**Comment by StrikerRUS** [comment] 2018-06-04 15:16
No chance we'll see SDK on the official website:

>Hi Andrey,
As I've been informed, the concerned team has decided to drop the support for APP SDK and hence, any related package on developer.amd.com might not be accessible anymore. Instead, they are recommending to use this lite SDK package available here: https://github.com/GPUOpen-LibrariesAndSDKs/OCL-SDK/releases
If I get more information about this, I'll share with you.
Regards,

https://community.amd.com/thread/228114#2863567

**Comment by guolinke** [comment] 2018-06-05 02:29
maybe the better solution is deploying the gpu test on Appveyor.
@StrikerRUS can you help for that? Thanks very much.

**Comment by StrikerRUS** [comment] 2018-06-05 10:13
@guolinke I'll give it a try.

The one thing I'm afraid is that Appveyor is **extremely** slow without concurrent jobs and GPU test will run for ages...

Does anyone familiar with Jenkins? There are machines with NVIDIA cards in it and we'll be able to run tests with CUDA. Guys from XGBoost do this: https://github.com/dmlc/xgboost/blob/master/Jenkinsfile

**Comment by StrikerRUS** [comment] 2018-06-06 03:55
@huanzhang12 Despite that GPU targeting table from docs says CUDA fails on any CPU, it seems that guys from OpenMM managed to compile and run tests with CUDA at Travis side:
https://github.com/pandegroup/openmm/blob/a885a6ae6bc14390f9540d383fbad8a58a087998/.travis.yml#L153
https://travis-ci.org/pandegroup/openmm/jobs/385865954

I decided to reproduce their successful experience, but LightGBM raises segmentation fault.
Could you please help to find what I've missed?
https://github.com/Microsoft/LightGBM/blob/dev3/.travis/test.sh
https://travis-ci.org/Microsoft/LightGBM/jobs/388563899

**Comment by StrikerRUS** [comment] 2018-06-09 13:37
Closed in #1428.

Despite the issue is already closed, it's interesting to me to hear from you @huanzhang12 about CUDA.

**Closed by StrikerRUS** 2018-06-09 13:37 UTC

**Comment by huanzhang12** [comment] 2018-06-11 04:28
@StrikerRUS It is impossible to test CUDA application on CPU. However, it is possible to test OpenCL applications on CPU as OpenCL aims portability and heterogeneous computing. The problem is that there is no good CPU backend implementation. The implementation in AMD APP SDK is actually pretty stable but AMD drops support. There is also an open source CPU backend, [pocl](http://portablecl.org), but based on my previous tests it cannot properly run LightGBM.

In OpenMM, when the CUDA build is tested, no CUDA related tests are run:
https://travis-ci.org/pandegroup/openmm/jobs/385865954#L3600
(only 25 tests and no GPU related tests)

On the other hand, in the OpenCL build, there are 147 tests and many of them are GPU-related:
https://travis-ci.org/pandegroup/openmm/jobs/385865952#L1411

So in fact, OpenMM also cannot run CUDA tests on travis CI. The way they run OpenCL tests is similar to ours, using AMD APP SDK.

For now, I suggest keep using AMD APP SDK as the testing environment.

BTW, there is a newer version of AMD APP SDK (v3.0.130.136) which can be downloaded here: https://community.amd.com/thread/228059. The current uploaded version (in v2.0.12 release) is an older release, v3.0.130.135, although I think the difference should be small.

**Comment by StrikerRUS** [comment] 2018-06-11 09:59
@huanzhang12 Thank you very much for the detailed answer!

>In OpenMM, when the CUDA build is tested, no CUDA related tests are run:

Yeah, that's what I've missed...
