### ISSUE TITLE
OSError: exception: access violation reading 0x0000000000000058

### ISSUE THREAD

**Issue by JoyB48** [microsoft/LightGBM#3047] opened 2020-05-04 06:49 UTC
I am using LightGBM for the first time and I am new to modelling. I am working on a classification problem with 3 classes. I am facing the OS error. I would request if anyone can help me with this.

## Environment info

Operating System: Windows 10

CPU/GPU model:  Intel (R) HD Graphics 620

Python version: Python 6.0.3

## Error message and / or logs

OSError: exception: access violation reading 0x0000000000000058

## Reproducible example(s)

X_train, X_test, y_train, y_test = train_test_split(x,y ,test_size=0.3, random_state= 0, stratify = y)

d_train = lgb.Dataset(X_train, label= y_train)

d_train

params = {}
params['learning_rate'] = 0.003
params['boosting_type'] = 'gbdt'
params['objective'] = 'multiclass'
params['metric'] = 'multi_logloss'
params['sub_feature'] = 0.5
params['num_leaves'] = 10
params['min_data'] = 50
params['max_depth'] = 10
params['num_class'] = 3

lgb_base = lgb.train(params, d_train, 100)

**Comment by jameslamb** [comment] 2020-05-10 05:54
Hello @JoyB48 , thanks for the report and for using `LightGBM`!

If you start a new Python session and run this code again, do you get the same error? We have seen this very rarely in our tests and it's often resolved by just starting a new Python session.

Also, since you mentioned you are new to this...to get your version of Python, you can run `python --version` from a command line or by running the following Python code

```python
import sys
print(sys.info)
```

**Closed** 2020-06-19 04:42 UTC
Labels: awaiting response

**Comment by fuwaraido** [comment] 2022-07-31 09:11
I reproduced this phenomenon. I don't know it caused by the same causes but here is my case. I'm using LightGBM with sklearn toolkits. So It maybe the different issues but this thread is the second top result of the error message, so I'll left some report here. If you think my report is inappropriate for resolving issue, please delete this post from the thread.

So here is the code.

```
from lightgbm import LGBMClassifier
from sklearn.pipeline import Pipeline
from sklearn.model_selection import cross_val_score
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.preprocessing import LabelEncoder

pipe = Pipeline([  
    ('vec', CountVectorizer(tokenizer=tokenizer)),
    ('clf', LGBMClassifier(boosting_type='goss'))  
])

le = LabelEncoder()
y = le.fit_transform(train.label)
X = train.text
scores = cross_val_score(pipe, X, y, scoring='neg_log_loss', cv=5)

==== Console out ====
Warning (from warnings module):
  File "D:\WPy64-3740\python-3.7.4.amd64\lib\site-packages\sklearn\model_selection\_validation.py", line 536
    FitFailedWarning)
FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: 
OSError: exception: access violation reading 0x00000000000002A8
```

The data I fed into the pipeline was pandas Series object. X contains some text paragraphs while y contains text labels. I'm running this code on IDLEX. This is my environment.

```
Python 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 20:34:20) [MSC v.1916 64 bit (AMD64)] on win32
Type "copyright", "credits" or "license()" for more information.
```
By the way, I'm not a big fun of Windows operating system. I just wanna play some games, that's all! 

After I encountered this error, I checked the output of CountVectorizer. Actually It is not a numpy array. CountVectorizer returns sparse matrix instead.

```
>>> CountVectorizer(tokenizer=tokenizer).fit_transform(train.text)
<30x62 sparse matrix of type '<class 'numpy.int64'>'
	with 666 stored elements in Compressed Sparse Row format>
```

I suspect this is the case of this exception and modify the code a little bit.

```
class DenseTransformer(TransformerMixin):
    def fit(self, X, y=None, **fit_params):
        return self
    def transform(self, X, y=None, **fit_params):
        return X.todense()

pipe = Pipeline([  
    ('vec', CountVectorizer(tokenizer=tokenizer)),
    ('dense', DenseTransformer()),
    ('clf', LGBMClassifier(boosting_type='goss'))  
])
```

The it worked, fine.

I really don't read LGBM carefully but in my case, sparse matrix was the cause of the exception. I hope it helps anybody who's looking for a workaround. Maybe LGBM.fit method should check input data a bit more carefully, if it doesn't support sparse matrix.

That's all I found about the problem. 

Thank you.

**Comment by jameslamb** [comment] 2022-08-20 02:43
Thanks for posting here @fuwaraido . Unfortunately, the code you've provided is not a self-contained example that could be used to investigate this issue.

For that, we'd need:

* the actual content of `train`
* the code for `tokenizer`
* information about the version of LightGBM you used and how you installed it

> I don't know it supports sparse matrix or not

LightGBM does support sparse matrices, including in its Python and R interfaces.
