### ISSUE TITLE
Cannot get good regression result on small trivial data

### ISSUE THREAD

**Issue by jcrosskey** [Microsoft/LightGBM#547] opened 2017-05-25 17:40 UTC
## Environment info
Operating System: Linux-4.4.0-77-generic-x86_64-with-debian-stretch-sid (Ubuntu)
CPU: x86_64
Python version: 2.7.12
LightGBM: v2.0 release

I ran a trivial small example where y value is well separated according to x values, but LightGBM failed to find the obvious solution. 

## Reproducible example
x = [  0.   1.   2.   3.   4.   5.   6.   7.   8.   9.  10.  11.  12.  13.  14.  15.] 
y = [ 0.1  0.1  0.1  0.1  0.2  0.2  0.2  0.2  0.3  0.3  0.3  0.3  0.4  0.4  0.4  0.4]

I expect the model to find the best solution easily. **Also, how is the number of bins and their boundaries determined?**

Code to reproduce:
```python
from lightgbm.basic import Dataset
import lightgbm as lgb
import numpy as np

data_size = 16
x = np.arange(data_size).astype(np.float).reshape(-1, 1)
y = np.repeat([0.1, 0.2, 0.3, 0.4], repeats=int(np.ceil(data_size / 4)))[:data_size]
x = x.reshape(data_size, -1)
train_data = Dataset(x, y)
param = dict(objective='regression',
             task='train',
             boosting='gbdt',
             num_iterations=1,
             learning_rate=1.0,
             num_leaves=4,
             tree_learner='serial',
             min_data_in_leaf=1,
             min_sum_hessian_in_leaf=0.1,
             boost_from_average=False,
             bagging_freq=0,
             feature_fraction=1.0,
             output_model='LGB_model.txt',
             is_sparse=False,
             is_training_metric=True,
             metric='mse',
             metric_freq=1)
gbm = lgb.train(param, train_data, num_boost_round=5,
                valid_sets=[train_data],
                valid_names=['train'], verbose_eval=1)
gbm.save_model('LGB_model.txt')
print(gbm.predict(x, pred_leaf=False, raw_score=True))
print(gbm.predict(x, pred_leaf=True))
```
Output:
```
[LightGBM] [Info] Total Bins 4
[LightGBM] [Info] Number of data: 16, number of used features: 1
[LightGBM] [Info] Trained a tree with leaves=4 and max_depth=2
[1]     train's l2: 0.002
[LightGBM] [Info] Trained a tree with leaves=4 and max_depth=3
[2]     train's l2: 0.002
[LightGBM] [Info] Trained a tree with leaves=4 and max_depth=2
[3]     train's l2: 0.002
[LightGBM] [Info] Trained a tree with leaves=4 and max_depth=2
[4]     train's l2: 0.002
[LightGBM] [Info] Trained a tree with leaves=4 and max_depth=2
[5]     train's l2: 0.002
[ 0.12        0.12        0.12        0.12        0.12        0.24000001
  0.24000001  0.24000001  0.24000001  0.24000001  0.36000001  0.36000001
  0.36000001  0.36000001  0.36000001  0.40000001]
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [2 1 3 2 3]
 [2 1 3 2 3]
 [2 1 3 2 3]
 [2 1 3 2 3]
 [2 1 3 2 3]
 [1 3 1 1 1]
 [1 3 1 1 1]
 [1 3 1 1 1]
 [1 3 1 1 1]
 [1 3 1 1 1]
 [3 2 2 3 2]]
```

**Comment by Laurae2** [comment] 2017-05-25 18:06
Reproducible issue starting from v2.0 but not happening on v1.

v1 gets correct results:

```r
> print(predict(model, data = x))
LightGBM] [Info] No further splits with positive gain, best gain: 0.000000, leaves: 1
[LightGBM] [Info] Stopped training because there are no more leafs that meet the split requirements.
 [1] 0.1 0.1 0.1 0.1 0.2 0.2 0.2 0.2 0.3 0.3 0.3 0.3 0.4 0.4 0.4 0.4
```

v2.0 gets incorrect results:

```r
> print(predict(model, data = x))
[LightGBM] [Info] No further splits with positive gain, best gain: -inf
[LightGBM] [Info] Trained a tree with leaves=4 and max_depth=2
 [1] 0.12 0.12 0.12 0.12 0.12 0.24 0.24 0.24 0.24 0.24 0.36 0.36 0.36 0.36 0.36 0.40
```

Code used:

```r
library(lightgbm)

x <- matrix(0:15, ncol = 1) + 1e-8
y <- as.numeric(floor(x / 4) * 0.1 + 0.1)
data <- lgb.Dataset(data = x, label = y)
model <- lgb.train(list(objective = "regression",
                        learning_rate = 1.0,
                        num_leaves = 255,
                        min_data = 1,
                        min_hessian = 1e-10,
                        boost_from_average = FALSE,
                        is_sparse = FALSE,
                        is_training_metric = TRUE,
                        metric = "l2",
                        metric_freq = 1,
                        num_threads = 1),
                   data,
                   10,
                   verbose = 2)
print(predict(model, data = x))
print(predict(model, data = x, predleaf = TRUE))
```

Elements:

```r
> matrix(0:15, ncol = 1) + 1e-8
         [,1]
 [1,] 1.0e-08
 [2,] 1.0e+00
 [3,] 2.0e+00
 [4,] 3.0e+00
 [5,] 4.0e+00
 [6,] 5.0e+00
 [7,] 6.0e+00
 [8,] 7.0e+00
 [9,] 8.0e+00
[10,] 9.0e+00
[11,] 1.0e+01
[12,] 1.1e+01
[13,] 1.2e+01
[14,] 1.3e+01
[15,] 1.4e+01
[16,] 1.5e+01
> as.numeric(floor(x / 4) * 0.1 + 0.1)
 [1] 0.1 0.1 0.1 0.1 0.2 0.2 0.2 0.2 0.3 0.3 0.3 0.3 0.4 0.4 0.4 0.4
```

**Comment by guolinke** [comment] 2017-05-26 00:22
@Laurae2 @jcrosskey 
try to set ```min_data_in_bin=1``` ?

**Comment by Laurae2** [comment] 2017-05-26 06:23
@guolinke I was already using `min_data = 1`

**Comment by Laurae2** [comment] 2017-05-26 07:30
Ah never mind, I thought it was another parameter.

```r
> print(predict(model, data = x))
 [1] 0.1 0.1 0.1 0.1 0.2 0.2 0.2 0.2 0.3 0.3 0.3 0.3 0.4 0.4 0.4 0.4
```

Issue is fixed with `min_data_in_bin = 1`. Reproducible code for correctness:

```r
library(lightgbm)

x <- matrix(0:15, ncol = 1) + 1e-8
y <- as.numeric(floor(x / 4) * 0.1 + 0.1)
data <- lgb.Dataset(data = x, label = y)
model <- lgb.train(list(objective = "regression",
                        learning_rate = 1.0,
                        num_leaves = 255,
                        min_data = 1,
                        min_hessian = 1e-10,
                        boost_from_average = FALSE,
                        is_sparse = FALSE,
                        is_training_metric = TRUE,
                        metric = "l2",
                        metric_freq = 1,
                        num_threads = 1,
                        min_data_in_bin = 1),
                   data,
                   10,
                   verbose = 2)
print(predict(model, data = x))
```

@guolinke We may add the Python code as a test case I think (who is maintaining Python test cases currently?). LightGBM should always get correct such trivial example.

**Comment by Laurae2** [comment] 2017-05-26 09:49
Can also confirm v2.0 is not affected by this issue.

```r
> print(predict(model, data = x))
 [1] 0.1 0.1 0.1 0.1 0.2 0.2 0.2 0.2 0.3 0.3 0.3 0.3 0.4 0.4 0.4 0.4
```

**Closed** 2017-05-26 10:29 UTC

**Comment by jcrosskey** [comment] 2017-05-26 12:59
Thanks! Should I always use `min_data_in_bin=1` in parameter configuration?

**Comment by guolinke** [comment] 2017-05-26 13:03
@jcrosskey of course not. ```min_data_in_bin``` can improve the generalization ability.

**Comment by jcrosskey** [comment] 2017-05-26 13:26
@guolinke Got it, I should only use it when I know I want small number of data points in some bin, otherwise bigger `min_data_in_bin` generalizes better.

**Comment by sid1898** [comment] 2019-11-17 10:21
@Laurae2 what is the reason behind the jcrosskey model not giving the expected result.
