### ISSUE TITLE
install lightgbm failed on macos m2 pro

### ISSUE THREAD

**Issue by nzhsta** [microsoft/LightGBM#5876] opened 2023-05-08 16:40 UTC
## Description
install lightgbm failed

## Environment info
py3.6

Command(s) you used to install LightGBM

```shell
git clone --recursive https://github.com/microsoft/LightGBM
cd LightGBM
sh build-python.sh install
```

## output
```shell
building lightgbm
--- building wheel ---
INFO:root:running bdist_wheel
setup.py:195: SetuptoolsDeprecationWarning: setup.py install is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` directly.
        Instead, use pypa/build, pypa/installer, pypa/build or
        other standards-based tools.

        See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
        ********************************************************************************

!!
  install.initialize_options(self)
INFO:root:running build
INFO:root:running build_py
INFO:root:creating build
INFO:root:creating build/lib
INFO:root:creating build/lib/lightgbm
INFO:root:copying lightgbm/callback.py -> build/lib/lightgbm
INFO:root:copying lightgbm/compat.py -> build/lib/lightgbm
INFO:root:copying lightgbm/plotting.py -> build/lib/lightgbm
INFO:root:copying lightgbm/__init__.py -> build/lib/lightgbm
INFO:root:copying lightgbm/engine.py -> build/lib/lightgbm
INFO:root:copying lightgbm/dask.py -> build/lib/lightgbm
INFO:root:copying lightgbm/basic.py -> build/lib/lightgbm
INFO:root:copying lightgbm/libpath.py -> build/lib/lightgbm
INFO:root:copying lightgbm/sklearn.py -> build/lib/lightgbm
INFO:root:running egg_info
INFO:root:creating lightgbm.egg-info
INFO:root:writing lightgbm.egg-info/PKG-INFO
INFO:root:writing dependency_links to lightgbm.egg-info/dependency_links.txt
INFO:root:writing requirements to lightgbm.egg-info/requires.txt
INFO:root:writing top-level names to lightgbm.egg-info/top_level.txt
INFO:root:writing manifest file 'lightgbm.egg-info/SOURCES.txt'
INFO:root:reading manifest file 'lightgbm.egg-info/SOURCES.txt'
INFO:root:reading manifest template 'MANIFEST.in'
WARNING:root:no previously-included directories found matching 'build'
WARNING:root:warning: no files found matching '*.txt'
WARNING:root:warning: no files found matching '*.so' under directory 'lightgbm'
WARNING:root:warning: no files found matching '*.so' under directory 'compile'
WARNING:root:warning: no files found matching '*.dll' under directory 'compile/Release'
WARNING:root:warning: no files found matching '*.dll' under directory 'compile/windows/x64/DLL'
WARNING:root:warning: no previously-included files matching '*.py[co]' found anywhere in distribution
WARNING:root:warning: no previously-included files found matching 'compile/external_libs/compute/.git'
INFO:root:adding license file 'LICENSE'
INFO:root:writing manifest file 'lightgbm.egg-info/SOURCES.txt'
INFO:root:copying lightgbm/VERSION.txt -> build/lib/lightgbm
INFO:root:copying lightgbm/py.typed -> build/lib/lightgbm
INFO:root:installing to build/bdist.macosx-10.9-x86_64/wheel
INFO:root:running install
INFO:LightGBM:Starting to compile the library.
INFO:LightGBM:Starting to compile with CMake.
Traceback (most recent call last):
  File "setup.py", line 61, in silent_call
    subprocess.check_call(cmd, stderr=log, stdout=log)
  File "/Users/jarven/environment/anaconda3/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['make', '_lightgbm', '-I/Users/jarven/LightGBM/lightgbm-python/build_cpp', '-j4']' returned non-zero exit status 2.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 355, in <module>
    'Typing :: Typed'])
  File "/Users/jarven/environment/anaconda3/lib/python3.7/site-packages/setuptools/__init__.py", line 107, in setup
    return distutils.core.setup(**attrs)
  File "/Users/jarven/environment/anaconda3/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
  File "/Users/jarven/environment/anaconda3/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/Users/jarven/environment/anaconda3/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "/Users/jarven/environment/anaconda3/lib/python3.7/site-packages/setuptools/dist.py", line 1244, in run_command
    super().run_command(command)
  File "/Users/jarven/environment/anaconda3/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/Users/jarven/environment/anaconda3/lib/python3.7/site-packages/wheel/bdist_wheel.py", line 259, in run
    self.run_command('install')
  File "/Users/jarven/environment/anaconda3/lib/python3.7/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/Users/jarven/environment/anaconda3/lib/python3.7/site-packages/setuptools/dist.py", line 1244, in run_command
    super().run_command(command)
  File "/Users/jarven/environment/anaconda3/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "setup.py", line 228, in run
    time_costs=self.time_costs)
  File "setup.py", line 175, in compile_cpp
    error_msg='An error has occurred while building lightgbm library file')
  File "setup.py", line 65, in silent_call
    raise Exception("\n".join((error_msg, LOG_NOTICE)))
Exception: An error has occurred while building lightgbm library file
The full version of error log was saved into /Users/jarven/LightGBM_compilation.log
```

**Comment by jameslamb** [comment] 2023-05-12 20:21
Thanks for using LightGBM.

I'm closing this and marking it as a duplicate of #5700. This is the exact same issue and error message as was reported there. In the future, please search the open issues in this project before opening a new one.

See my response there for why this has not yet been fixed: https://github.com/microsoft/LightGBM/issues/5700#issuecomment-1424394742. I'm sorry for the inconvenience, and I hope we'll be able to get LightGBM working on the new Macs soon.

**Closed by jameslamb** 2023-05-12 20:21 UTC
Labels: duplicate, question
