### ISSUE TITLE
Crash when use more than 8GB data for training

### ISSUE THREAD

**Issue by Anstinus** [microsoft/LightGBM#4853] opened 2021-12-04 07:54 UTC
I'm using C API. When the training dataset is too large, the program would just crash when I call 'LGBM_BoosterCreate()'
(As a reference, I found a similar issue #4480 but there is no answer to that.)

With 7.5GB data, it works fine:

> [LightGBM] [Info] This is the GPU trainer!!
> [LightGBM] [Info] Total Bins 830854
> [LightGBM] [Info] Number of data points in the train set: 2413300, number of used features: 3273
> [LightGBM] [Info] Using requested OpenCL platform 0 device 0
> [LightGBM] [Info] Using GPU Device: NVIDIA GeForce RTX 3090, Vendor: NVIDIA Corporation
> [LightGBM] [Info] Compiling OpenCL Kernel with 256 bins...
> [LightGBM] [Info] GPU programs have been built
> [LightGBM] [Info] Size of histogram bin entry: 8
> [LightGBM] [Info] 3273 dense feature groups (7539.72 MB) transferred to GPU in 2.319649 secs. 0 sparse feature groups

If I add more data (estimate ~8.9GB), It would crash before the last line:

> [LightGBM] [Info] This is the GPU trainer!!
> [LightGBM] [Info] Total Bins 939820
> [LightGBM] [Info] Number of data points in the train set: 2413300, number of used features: 3702
> [LightGBM] [Info] Using requested OpenCL platform 0 device 0
> [LightGBM] [Info] Using GPU Device: NVIDIA GeForce RTX 3090, Vendor: NVIDIA Corporation
> [LightGBM] [Info] Compiling OpenCL Kernel with 256 bins...
> [LightGBM] [Info] GPU programs have been built
> [LightGBM] [Info] Size of histogram bin entry: 8
> _>> Crash here. No log any more_

And it happens either when I increase number of features or number of data points, as long as the total size is more than ~8GB.
I'm using 
LightGbm v3.3.1 C API
CUDA 11.5.56
RTX 3090 with 24GB memory

**Comment by jameslamb** [comment] 2021-12-04 16:00
Thanks for using LightGBM! But you're right, this is a duplicate of #4480. Please don't open new issues just because of lack of discussion on another one.

I'm going to close this, can you please add this detail as a comment on #4480 ?

**Closed by jameslamb** 2021-12-04 16:00 UTC
