### ISSUE TITLE
[CLI] Socket-based distributed training fails

### ISSUE THREAD

**Issue by wil70** [microsoft/LightGBM#6117] opened 2023-09-29 04:40 UTC
Hello,

I'm trying to run a distributed training with 2 machines.
I'm using LightGBM CLI with the socket distributed option.
I compile the latest c++ code as of today.

The **config** on both machines look like this:
```
...
tree_learner=voting

# number of machines in parallel training, alias: num_machine
num_machines = 2

# local listening port in parallel training, alias: local_port
local_listen_port = 12400

# machines list file for parallel training, alias: mlist
machine_list_file = mlist.txt

```

the **mlist.tx**t look like this:
```
machine_1_ip 12400
machine_2_ip 12400

```
I open the firewall for private and domaine on both machines.

**Machine 1 output**
```
[LightGBM] [Info] Finished loading parameters
[LightGBM] [Info] Trying to bind port 12400...
[LightGBM] [Info] Binding port 12400 succeeded
[LightGBM] [Info] Listening...

```

**Machine 2 output**
```

[LightGBM] [Info] Finished loading parameters
[LightGBM] [Info] Trying to bind port 12400...
[LightGBM] [Info] Binding port 12400 succeeded
[LightGBM] [Info] Listening...[LightGBM] [Warning] Connecting to rank 1 failed, waiting for 200 milliseconds

[LightGBM] [Warning] Connecting to rank 1 failed, waiting for 260 milliseconds
[LightGBM] [Warning] Connecting to rank 1 failed, waiting for 338 milliseconds
[LightGBM] [Warning] Connecting to rank 1 failed, waiting for 439 milliseconds
[LightGBM] [Warning] Connecting to rank 1 failed, waiting for 570 milliseconds
[LightGBM] [Warning] Connecting to rank 1 failed, waiting for 741 milliseconds
[LightGBM] [Warning] Connecting to rank 1 failed, waiting for 963 milliseconds
[LightGBM] [Warning] Connecting to rank 1 failed, waiting for 1251 milliseconds
[LightGBM] [Warning] Connecting to rank 1 failed, waiting for 1626 milliseconds
[LightGBM] [Warning] Connecting to rank 1 failed, waiting for 2113 milliseconds
[LightGBM] [Warning] Connecting to rank 1 failed, waiting for 2746 milliseconds
[LightGBM] [Warning] Connecting to rank 1 failed, waiting for 3569 milliseconds
[LightGBM] [Warning] Connecting to rank 1 failed, waiting for 4639 milliseconds
[LightGBM] [Warning] Connecting to rank 1 failed, waiting for 6030 milliseconds
[LightGBM] [Warning] Connecting to rank 1 failed, waiting for 7838 milliseconds
[LightGBM] [Warning] Connecting to rank 1 failed, waiting for 10189 milliseconds
[LightGBM] [Warning] Connecting to rank 1 failed, waiting for 13245 milliseconds
[LightGBM] [Warning] Connecting to rank 1 failed, waiting for 17218 milliseconds
[LightGBM] [Warning] Connecting to rank 1 failed, waiting for 22383 milliseconds
[LightGBM] [Warning] Connecting to rank 1 failed, waiting for 29097 milliseconds
[LightGBM] [Info] Local rank: 0, total number of machines: 2
[LightGBM] [Info] Finished initializing network
```

Any idea what I should check?

thanks for your help

Wil

**Comment by jameslamb** [comment] 2023-09-29 13:57
Thanks for using LightGBM.

I'm confused... what specific problem are you reporting? The issue title suggests that you're concerned about the warnings shown in machine 2's logs, but what I see there is that it did eventually find the other worker and successfully form the network.

Did you omit some logs for machine 1? Or are you saying that after `Listening....` the process on machine 1 crashed or timed out?

We need more details to help you.

**Comment by wil70** [comment] 2023-09-29 17:32
Thanks @jameslamb 
Let me rename the title and describe a bit more, thanks for the feedback

This is the full log, so machine 2 exit the process and no training has been done.
I downlaoded the full code, compile it again and same result.

As I recall it working a year ago, I look at my backup and found an old lightgbm.exe, I copy it over and it worked right away. I'm using this example to simplify https://github.com/microsoft/lightgbm/tree/master/examples/parallel_learning

### **Old code from 2022** (note: I waited 1 min before starting the second lightgbm on the 2nd machine)
![image](https://github.com/microsoft/LightGBM/assets/7807709/600e55af-50fe-4e14-8845-ba97c9e2b7d7)
**It completed the training**

### **New code 2023**
![image](https://github.com/microsoft/LightGBM/assets/7807709/f7ed144d-59ed-4c40-a41b-8ac51f40f4ad)
**It not start the training and the process seems to have crash at the end on the second machine**

It seems there is something fishy with the latest code concerning Distributed with Socket
Let me know if you want me to run some test

Thanks for your help

Wil

**Comment by wil70** [comment] 2023-09-29 18:36
Note: I also ran with "tree_learner = serial" with both versions of lightGBM v2022_10 and latest 2023 and they both completed and gave the same result which is great!
So the only concern is Distributed with Docket

**Comment by jacopocecch** [comment] 2023-10-26 15:32
Hi, I also have the same issue

**Comment by jmoralez** [comment] 2023-10-26 16:59
Linking #5159 since it was a change for the socket configuration in Windows. That's the only change to this that I remember, @shiyu1994 do you think that could cause the problem here?

**Comment by jacopocecch** [comment] 2023-10-27 08:49
@jmoralez I'm using a MacOS machine and a Linux one for training.

**Comment by wil70** [comment] 2023-11-12 17:48
@jacopocecch right now I'm using the old solution, 
For info, I'm on windows. 

I will pull the latest code and try again.

**Comment by wil70** [comment] 2023-11-14 01:16
@jacopocecch I compiled latest code from today on windows and it seems to work well. I also check the model by comparing the result to Oct 2022 and it is the same - so all good! :))

Some number with the the parrallel_learning_example from git
I change for 1000 iterations/num_trees at 0.01 learning_rate 

**for serial**
```
[LightGBM] [Info] Iteration:1000, training binary_logloss : 0.217513
[LightGBM] [Info] Iteration:1000, training auc : 0.999187
[LightGBM] [Info] Iteration:1000, valid_1 binary_logloss : 0.494112
[LightGBM] [Info] Iteration:1000, valid_1 auc : 0.840815
[LightGBM] [Info] 16.303107 seconds elapsed, finished iteration 1000
[LightGBM] [Info] Finished training
```

**for feature**
```
[LightGBM] [Info] Iteration:1000, training binary_logloss : 0.217513
[LightGBM] [Info] Iteration:1000, training auc : 0.999187
[LightGBM] [Info] Iteration:1000, valid_1 binary_logloss : 0.494112
[LightGBM] [Info] Iteration:1000, valid_1 auc : 0.840815
[LightGBM] [Info] 43.695520 seconds elapsed, finished iteration 1000
[LightGBM] [Info] Finished training
[LightGBM] [Info] Finished linking network in 40.289819 seconds
```

**for data** 
```
[LightGBM] [Info] Iteration:1000, training binary_logloss : 0.214978
[LightGBM] [Info] Iteration:1000, training auc : 0.999072
[LightGBM] [Info] Iteration:1000, valid_1 binary_logloss : 0.491479
[LightGBM] [Info] Iteration:1000, valid_1 auc : 0.841767
[LightGBM] [Info] 189.375081 seconds elapsed, finished iteration 1000
[LightGBM] [Info] Finished training
[LightGBM] [Info] Finished linking network in 184.785459 seconds
```

**for Voting**
```
[LightGBM] [Info] Iteration:1000, training binary_logloss : 0.215433
[LightGBM] [Info] Iteration:1000, training auc : 0.999089
[LightGBM] [Info] Iteration:1000, valid_1 binary_logloss : 0.491557
[LightGBM] [Info] Iteration:1000, valid_1 auc : 0.840541
[LightGBM] [Info] 256.181240 seconds elapsed, finished iteration 1000
[LightGBM] [Info] Finished training
[LightGBM] [Info] Finished linking network in 245.827818 seconds
```
Note: my machines were already busy, so I took the slowest score for the serial, I might redo this test once the machine are done with their current work.

Note: For info the mpi version doesn't compile with the latest code on windows, it is missing the mpi.h file (I'm nt using it as I'm using the socket version)

Thanks @jameslamb @jmoralez @jacopocecch and @shiyu1994 ! 

We can close this thread.

**Comment by jameslamb** [comment] 2023-11-14 02:41
> Would the mpi version be way faster than socket?

Not necessarily. The MPI version exists specifically for users who are working in an environment where MPI programs are the main supported pattern for analytical workloads, e.g. for those using Slurm as a workload manager ([docs](https://slurm.schedmd.com/mpi_guide.html)).

So it is there to allow LightGBM training to look and feel like users' other workloads... "be faster than other approaches" is not one of its design goals.

> For info the mpi version doesn't compile with the latest code on windows, it is missing the mpi.h file

We'd welcome a **separate** bug report with **a specific, minimal, reproducible example** describing exactly what you're talking about. If you choose to open that, please provide evidence that it's a bug in LightGBM and not just that you've installed the MPI headers in a non-standard location or failed to install them at all.

> We can close this thread.

Great, we will close this.

**Closed by jameslamb** 2023-11-14 02:41 UTC
Labels: question
