### ISSUE TITLE
prebuilt gpu/cuda version for python

### ISSUE THREAD

**Issue by 7starsea** [microsoft/LightGBM#3490] opened 2020-10-27 01:31 UTC
I use  `pip install lightgbm`, and when I run the train api with device=gpu, there is an error "recompile with CMake option -DUSE_GPU=1" .

do we have a prebuilt gpu/cuda version for python-package?

Thanks.

**Comment by StrikerRUS** [comment] 2020-10-27 01:34
No, we haven't. Windows wheels will gain in-built GPU support after merging #3403 .

**Comment by 7starsea** [comment] 2020-10-27 01:44
> No, we haven't. Windows wheels will gain in-built GPU support after merging #3403 .

I wish linux wheels would also gain in-build GPU support.

**Comment by StrikerRUS** [comment] 2020-10-27 02:55
It is possible. Please refer to https://github.com/microsoft/LightGBM/pull/3403#issuecomment-708040308.

**Comment by StrikerRUS** [comment] 2020-10-28 13:58
Closing as a duplicate of #2263.

**Closed by StrikerRUS** 2020-10-28 13:58 UTC
