### ISSUE TITLE
pred_contrib doesn't add up to the prediction value (for some objective functions)

### ISSUE THREAD

**Issue by mlisovyi** [microsoft/LightGBM#5568] opened 2022-11-03 09:16 UTC
## Description
As the title says, `pred_contrib` output doesn't add up to the actual prediction.
The problem seems to be related to the choice of the objective function for a regression model, in particular affected are `poisson`, `gamma` and `tweedie`.
This happens with `tree-linear=False` (as it is the default and I don't change it).

## Reproducible example
```python
import lightgbm as lgb
import pandas as pd
from sklearn.datasets import load_boston


data = load_boston()
X = pd.DataFrame(data.data, columns=data.feature_names)
# scale the target to make the difference more pronounced
y = data.target * 1000

# try out different objective functions and for each compare prediction with the sum of feature contributions
for obj in ["l2", "l1", "huber", "fair", "poisson", "mape", "gamma", "tweedie"]:
    model = lgb.LGBMRegressor(objective=obj).fit(X, y)
    preds = model.predict(X)

    shap_values = model.predict(X, pred_contrib=True)
    sum_of_shap = shap_values.sum(axis=1)

    diff = preds - sum_of_shap
    # print out the difference between the sum and the prediction *for the first sample*
    print(
        f"{obj}: Difference= {diff[0] / preds[0]:.1%}.    Prediction = {preds[0]:.1f}, sum of shap values = {sum_of_shap[0]:.1f}"
    )
```
Output: 
```
l2: Difference= -0.0%.    Prediction = 24274.4, sum of shap values = 24274.4
l1: Difference= -0.0%.    Prediction = 25055.9, sum of shap values = 25055.9
huber: Difference= 0.0%.    Prediction = 22541.8, sum of shap values = 22541.8
fair: Difference= 0.0%.    Prediction = 57641.8, sum of shap values = 57641.8
poisson: Difference= 100.0%.    Prediction = 24978.1, sum of shap values = 10.1
mape: Difference= -0.0%.    Prediction = 25148.8, sum of shap values = 25148.8
gamma: Difference= 100.0%.    Prediction = 24221.7, sum of shap values = 10.1
tweedie: Difference= 100.0%.    Prediction = 24475.2, sum of shap values = 10.1
```

## Environment info

LightGBM version or commit hash:

lightgbm = 3.3.3

Command(s) you used to install LightGBM

```shell
conda install lightgbm
```

python = 3.8

## Additional Comments
The problem is related or same as in #3998, but that issue is closed and I have no right to re-open it. Feel free to close this one, if you prefer to re-open and follow-up in the previous.

**Comment by jameslamb** [comment] 2022-11-03 14:23
I'm going to close and lock this as a duplicate of #3998. I've reopened #3998, and let's keep the discussion focused there.

You can trust that when you comment on a closed issue, every maintainer (and in fact many of the 450 watchers on the repo) will be notified.

**Closed by jameslamb** 2022-11-03 14:23 UTC
