### ISSUE TITLE
[python] Can't load dataset from file and write out binary to new filename

### ISSUE THREAD

**Issue by ebernhardson** [Microsoft/LightGBM#1136] opened 2017-12-23 08:05 UTC
For bugs and unexpected issues, please provide following information, so that we could reproduce on our system.

## Environment info
Operating System: Debian Stretch
CPU: Intel E5-2640v4
C++/Python/R version: python 2.7 (package from pypi. Also tried with lightgbm compiled with g++ 5.4.0)

## Error Message:
[LightGBM] [Warning] Bianry file /tmp/tmpmueIv2 already existed

## Reproducible examples

import lightgbm
ds = lightgbm.Dataset('/path/to/dataset')
ds.save_binary('/path/to/dataset-new')

When creating the dataset:
  python calls LGBM_DatasetCreateFromFile with a const char* filename
  DatasetLoader::LoadFromFile is called with filename (uncopied)
  DatasetLoader new's up a dataset and sets the filename (still uncopied) to dataset->data_filename_
  control is returned to python

I'm not super familiar with python ctypes, but setting some gdb break points i can see the memory address for the passed strings is being reused. The call to LGBM_DatasetCreateFromFile and LGBM_DatasetSaveBinary are getting the exact same const char *filename memory address, although the contents changes between the two calls. This also seems to depend on how it's called. If i pass a constant string typed into the interactive console different memory addresses will be passed, but with the below example using tempfiles (as the data is only munged locally and then stored on hdfs for later usage).  In general it doesn't seem safe to expect a character string passed python will keep it's value.

## Steps to reproduce

```
gdb venv/bin/python
(gdb) break LGBM_DatasetSaveBinary
(gdb) break LGBM_DatasetCreateFromFile
(gdb) run
>>> import lightgbm
>>> import tempfile
>>> with tempfile.NamedTemporaryFile() as f:
>>>    subprocess.check_call(['hdfs', 'dfs', '-text', '/path/to/libsvmdata/*'], stdout=f.file)
>>>    ds = lightgbm.Dataset(f.name).construct()
Thread 1 "python" hit Breakpoint 2, LGBM_DatasetCreateFromFile (filename=0x7fff90f1b6e4 "/tmp/tmp8FXSd4", parameters=0x7fff90f24094 "query_column=1 verbose=1",
    reference=0x0, out=0x7fff90f1f1c0) at /home/ebernhardson/git/LightGBM/src/c_api.cpp:357
357     /home/ebernhardson/git/LightGBM/src/c_api.cpp: No such file or directory.
(gdb) continue
>>> with tempfile.NamedTemporaryFile() as f:
>>>   os.unlink(f.name)
>>>   ds.save_binary(f.name)
Thread 1 "python" hit Breakpoint 1, LGBM_DatasetSaveBinary (handle=0x555556259d90, filename=0x7fff90f1b6e4 "/tmp/tmpRiR9h0")
    at /home/ebernhardson/git/LightGBM/src/c_api.cpp:742
742     in /home/ebernhardson/git/LightGBM/src/c_api.cpp
(gdb)
```

**Comment by guolinke** [comment] 2017-12-23 10:50
sorry, I didn't get your point. 
I just try this on example data: https://github.com/Microsoft/LightGBM/tree/master/examples/regression

code:
```
>>> import lightgbm as lgb
>>> data = lgb.Dataset("regression.train")
>>> data.construct()
<lightgbm.basic.Dataset object at 0x00000236312BA2E8>
>>> data.save_binary("test.bin")
[LightGBM] [Info] Saving data to binary file test.bin
```

everything is fine. I don't know what is your problem.

**Comment by ebernhardson** [comment] 2017-12-23 17:15
To recreate the problem simply:
```
>>> import lightgbm
>>> import shutil
>>> with tempfile.NamedTemporaryFile() as out, open('regression.train') as input:
...   shutil.copyfileobj(input, out)
...   ds = lightgbm.Dataset(out.name).construct()
...
[LightGBM] [Info] Warning: last line of /tmp/tmpISTsM3 has no end of line, still using this line
>>> with tempfile.NamedTemporaryFile() as f:
...   ds.save_binary(f.name)
...
[LightGBM] [Warning] File /tmp/tmpJ7iA_3 existed, cannot save binary to it
```

The problem from my GDB output above is that the memory address of filename gets reused. We can see in the first call we have `filename=0x7fff90f1b6e4 "/tmp/tmp8FXSd4"`  and in the second call `filename=0x7fff90f1b6e4 "/tmp/tmpRiR9h0"`.  Same memory address, different contents. In general it's not safe to expect that a string passed by python ctypes will keep its value, the memory can be reused depending on context.

**Comment by guolinke** [comment] 2017-12-24 00:54
I think the problem isnt in lightgbm side. 
subprocess may is the reason.

**Comment by guolinke** [comment] 2017-12-24 01:31
just run this in windows 10 times, and didn't meet the problem:
```
import lightgbm
import os
import distutils
import tempfile
import time
from distutils import file_util

with tempfile.NamedTemporaryFile() as f:
  f.close()
  distutils.file_util.copy_file('regression.train', f.name)
  time.sleep(10)
  ds = lightgbm.Dataset(f.name).construct()

with tempfile.NamedTemporaryFile() as f:
  f.close()
  ds.save_binary(f.name)
```

I think maybe you didn't use `NamedTemporaryFile` correctly. In windows, I need to close it otherwise I cannot delete it. Not sure about this in linux.

**Closed** 2017-12-24 01:39 UTC

**Comment by ebernhardson** [comment] 2017-12-24 23:44
The problem here is that lightgbm isn't copying the string content, it takes a `const char *` from python and assigns it to a member variable of the LightGBM::Metadata in the C++ side without ever copying it. I did a quick test and changing the `data_filename_` variable in Metadata from `const char *` to `std::string`, which does copy the string, resolves the problem. I did some digging around in the cpython codebase and the ctypes library only guarantees that a pointer is valid until the object representing the pointer on the python side is collected. Because of how LGBM_DatasetCreateFromFile is called this basically means the pointer is only valid until that function returns, after which the passed pointer is available to have new values written to it.  The data from that pointer needs to be copied to have a guarantee that the contents of the data_filename_ variable will not be replaced. What actual memory is used will certainly vary depending on the compiler used (gcc vs msvc vs clang, etc), possibly the version of python used, and other things.  The overall guarantee of the ctypes library though, that a pointer is valid until it is collected, will stay the same.

The difference with needing to close a file before deleting it is indeed a windows vs linux thing but unrelated to the issue shown here.

**Comment by guolinke** [comment] 2017-12-25 01:09
@ebernhardson metadata.data_filename_ really is a bug. 
However, it didn't cause this issue. 
The warning is thrown here: https://github.com/Microsoft/LightGBM/blob/master/src/io/dataset.cpp#L513-L517 , and the `data_filename_` is the member of Dataset class, which already is the std::string.

**Comment by ebernhardson** [comment] 2017-12-25 08:19
Perhaps the easiest way to demonstrate the issue is directly with C++:

```
#include "LightGBM/utils/log.h"
#include "LightGBM/c_api.h"

int main(int argc, char** argv) {
    char filename[128];
    char parameters[] = "";
    DatasetHandle handle;

    memset(filename, 0, 128);
    strcpy(filename, "regression.train");
    LGBM_DatasetCreateFromFile(filename, parameters, nullptr, &handle);
    memset(filename, 0, 128);
    strcpy(filename, "data not copied");
    LGBM_DatasetSaveBinary(handle, filename);
    return 0;
}
```

While you would not typically write code like this, it demonstrates the issue of the filename not being copied. This outputs the message:

```
[LightGBM] [Warning] Bianry file data not copied already existed 
```

The line that outputs that message is https://github.com/Microsoft/LightGBM/blob/master/src/io/dataset.cpp#L513-L517
```
  if (bin_filename != nullptr
      && std::string(bin_filename) == std::string(data_filename_)) {
    Log::Warning("Bianry file %s already existed", bin_filename);
    return;
  }
```

The only way for that example code using the lightgbm c api to output that message would be if lightgbm did not copy the input filename and is depending on the pointer passed in to remain constant (which is not guaranteed with the way the python code calls it)

**Comment by guolinke** [comment] 2017-12-25 10:07
@ebernhardson you are right. the Dataset.data_filename_ is const char* type, not std::string, which cause the problem. I already fix it in the latest commit. 
For the `THREAD_LOCAL` , it is defined in https://github.com/Microsoft/LightGBM/blob/master/include/LightGBM/utils/log.h#L14-L18
